'use client';

import React, { createContext, useContext, useEffect, useState } from 'react';

export type LanguageCode = 'EN' | 'HI' | 'TA' | 'TE' | 'BN' | 'MR' | 'GU' | 'KN';

interface LanguageContextType {
  language: LanguageCode;
  setLanguage: (lang: LanguageCode) => void;
  t: (key: string) => string;
}

const translations: Record<LanguageCode, Record<string, string>> = {
  EN: {},
  HI: {
    "Your Digital": "आपका डिजिटल",
    "Healthcare Ecosystem": "स्वास्थ्य सेवा पारिस्थितिकी तंत्र",
    "Book Consultation": "परामर्श बुक करें",
    "Health ATM": "हेल्थ एटीएम",
    "Digital Locker": "डिजिटल लॉकर",
    "Quick Access": "त्वरित पहुँच",
    "View All": "सभी देखें",
    "Consult Doctor": "डॉक्टर से परामर्श",
    "Order Medicines": "दवाएं ऑर्डर करें",
    "Book Lab Tests": "लैब टेस्ट बुक करें",
    "Manage Insurance": "बीमा प्रबंधित करें",
    "Training & Courses": "प्रशिक्षण और पाठ्यक्रम",
    "Hospitals": "अस्पताल",
    "Blood Bank": "ब्लड बैंक",
    "Organ Donation": "अंग दान",
    "QR Scanner": "क्यूआर स्कैनर",
    "Create ABHA Card": "आभा कार्ड बनाएं",
    "Live Health Dashboard": "लाइव्ह स्वास्थ्य डैशबोर्ड",
    "AI Alerts": "एआई अलर्ट",
    "Device Sync": "डिवाइस सिंक",
    "Telemedicine": "टेलीमेडिसिन",
    "Video / Audio Consultation": "वीडियो / ऑडियो परामर्श",
    "Connect with doctors instantly": "डॉक्टरों से तुरंत जुड़ें",
    "Join Now": "अभी जुड़ें",
    "Waiting Room": "प्रतीक्षा कक्ष",
    "Patients Ahead": "मरीज आगे हैं",
    "Est. 8 mins wait": "अनुमानित 8 मिनट प्रतीक्षा",
    "Multi-Doctor": "बहु-डॉक्टर",
    "Conference": "कॉन्फ्रेंस",
    "Connect with specialists": "विशेषज्ञों से जुड़ें",
    "Marketplace": "मार्केटप्लेस",
    "Medicine Delivery": "दवा वितरण",
    "Lab Booking": "लैब बुकिंग",
    "Home Sample Collection": "गृह नमूना संग्रह",
    "Medical Equipment": "चिकित्सा उपकरण",
    "Ambulance Booking": "एम्बुलेंस बुकिंग",
    "Drone Delivery": "ड्रोन डिलीवरी",
    "Coming Soon": "जल्द आ रहा है",
    "Medicolegal & Compliance": "मेडिकोलीगल और अनुपालन",
    "Medicolegal Support": "मेडिकोलीगल सहायता",
    "Digital Consent Forms": "डिजिटल सहमति पत्र",
    "Prescription Verification": "पर्चे का सत्यापन",
    "Secure Health Records": "सुरक्षित स्वास्थ्य रिकॉर्ड",
    "Telemedicine Compliance": "टेलीमेडिसिन अनुपालन",
    "Legal Docs Vault": "कानूनी दस्तावेज वॉल्ट",
    "ABDM Compliant": "ABDM अनुपालन",
    "HIPAA Secure": "HIPAA सुरक्षित",
    "GDPR Ready": "GDPR तैयार",
    "DPDP Compliant": "DPDP अनुपालन",
    "Health Insights & Education": "स्वास्थ्य अंतर्दृष्टि और शिक्षा",
    "Health Tips": "स्वास्थ्य युक्तियाँ",
    "Daily tips for a healthy life": "स्वस्थ जीवन के लिए दैनिक सुझाव",
    "Appointment Reminders": "अपॉइंटमेंट अनुस्मारक",
    "Never miss your appointments": "अपने अपॉइंटमेंट कभी न चूकें",
    "Preventive Care": "निवारक देखभाल",
    "Regular checkups for a better you": "बेहतर स्वास्थ्य के लिए नियमित जांच",
    "Chronic Disease Programs": "क्रोनिक बीमारी कार्यक्रम",
    "Specialized care for chronic conditions": "क्रोनिक स्थितियों के लिए विशेष देखभाल",
    "AI Health Assistant": "एआई स्वास्थ्य सहायक",
    "Your smart health companion": "आपका स्मार्ट स्वास्थ्य साथी",
    "Home": "होम",
    "Health": "स्वास्थ्य",
    "Appointments": "अपॉइंटमेंट",
    "Records": "रिकॉर्ड",
    "More": "अधिक"
  },
  TA: {
    "Your Digital": "உங்கள் டிஜிட்டல்",
    "Healthcare Ecosystem": "சுகாதார சுற்றுச்சூழல் அமைப்பு",
    "Book Consultation": "ஆலோசனை முன்பதிவு",
    "Health ATM": "சுகாதார ஏடிஎம்",
    "Digital Locker": "டிஜிட்டல் லாக்கர்",
    "Quick Access": "விரைவு அணுகல்",
    "View All": "அனைத்தையும் காட்டு",
    "Consult Doctor": "மருத்துவர் ஆலோசனை",
    "Order Medicines": "மருந்துகள் ஆர்டர்",
    "Book Lab Tests": "ஆய்வக சோதனை முன்பதிவு",
    "Manage Insurance": "காப்பீடு மேலாண்மை",
    "Training & Courses": "பயிற்சி மற்றும் படிப்புகள்",
    "Hospitals": "மருத்துவமனைகள்",
    "Blood Bank": "இரத்த வங்கி",
    "Organ Donation": "உறுப்பு தானம்",
    "QR Scanner": "கியூஆர் ஸ்கேனர்",
    "Create ABHA Card": "ஆபா அட்டை உருவாக்கு",
    "Live Health Dashboard": "நேரடி சுகாதார டேஷ்போர்டு",
    "AI Alerts": "AI விழிப்பூட்டல்கள்",
    "Device Sync": "சாதன ஒத்திசைவு",
    "Telemedicine": "டெலிமெடிசின்",
    "Video / Audio Consultation": "வீடியோ / ஆடியோ ஆலோசனை",
    "Connect with doctors instantly": "மருத்துவர்களுடன் உடனே இணையுங்கள்",
    "Join Now": "இப்போது இணையுங்கள்",
    "Waiting Room": "காத்திருப்பு அறை",
    "Patients Ahead": "நோயாளி முன்னே உள்ளனர்",
    "Est. 8 mins wait": "சுமார் 8 நிமிட காத்திருப்பு",
    "Multi-Doctor": "பல மருத்துவர்",
    "Conference": "மாநாடு",
    "Connect with specialists": "நிபுணர்களுடன் இணையுங்கள்",
    "Marketplace": "சந்தைப்பகுதி",
    "Medicine Delivery": "மருந்து விநியோகம்",
    "Lab Booking": "ஆய்வக முன்பதிவு",
    "Home Sample Collection": "வீட்டு மாதிரி சேகரிப்பு",
    "Medical Equipment": "மருத்துவ உபகரணங்கள்",
    "Ambulance Booking": "ஆம்புலன்ஸ் முன்பதிவு",
    "Drone Delivery": "ட்ரோன் விநியோகம்",
    "Coming Soon": "விரைவில் வரும்",
    "Medicolegal & Compliance": "மருத்துவச் சட்டம் & இணக்கம்",
    "Medicolegal Support": "சட்ட மருத்துவ ஆதரவு",
    "Digital Consent Forms": "டிஜிட்டல் ஒப்புதல் படிவங்கள்",
    "Prescription Verification": "மருந்துச்சீட்டு சரிபார்ப்பு",
    "Secure Health Records": "பாதுகாப்பான சுகாதார பதிவுகள்",
    "Telemedicine Compliance": "டெலிமெடிசின் இணக்கம்",
    "Legal Docs Vault": "சட்ட ஆவணங்கள் பாதுகாப்பு பெட்டகம்",
    "ABDM Compliant": "ABDM இணக்கமானது",
    "HIPAA Secure": "HIPAA பாதுகாப்பானது",
    "GDPR Ready": "GDPR தயாராக உள்ளது",
    "DPDP Compliant": "DPDP இணக்கமானது",
    "Health Insights & Education": "சுகாதார நுண்ணறிவு மற்றும் கல்வி",
    "Health Tips": "சுகாதார குறிப்புகள்",
    "Daily tips for a healthy life": "ஆரோக்கியமான வாழ்க்கைக்கான தினசரி குறிப்புகள்",
    "Appointment Reminders": "சந்திப்பு நினைவூட்டல்கள்",
    "Never miss your appointments": "உங்கள் சந்திப்புகளை தவறவிடாதீர்கள்",
    "Preventive Care": "தடுப்பு பராமரிப்பு",
    "Regular checkups for a better you": "சிறந்த ஆரோக்கியத்திற்கு வழக்கமான சோதனைகள்",
    "Chronic Disease Programs": "நாள்பட்ட நோய் திட்டங்கள்",
    "Specialized care for chronic conditions": "நாள்பட்ட நோய்களுக்கான சிறப்பு சிகிச்சை",
    "AI Health Assistant": "AI சுகாதார உதவியாளர்",
    "Your smart health companion": "உங்கள் ஸ்மார்ட் சுகாதார துணையாக",
    "Home": "முகப்பு",
    "Health": "சுகாதாரம்",
    "Appointments": "சந்திப்புகள்",
    "Records": "பதிவுகள்",
    "More": "மேலும்"
  },
  TE: {
    "Your Digital": "మీ డిజిటల్",
    "Healthcare Ecosystem": "ఆరోగ్య సంరక్షణ వ్యవస్థ",
    "Book Consultation": "సంప్రదింపు బుక్ చేయండి",
    "Health ATM": "ヘల్త్ ఏటిఎం",
    "Digital Locker": "డిజిటల్ లాకర్",
    "Quick Access": "త్వరిత యాక్సెస్",
    "View All": "అన్నీ చూడండి",
    "Consult Doctor": "వైద్యుడిని సంప్రదించండి",
    "Order Medicines": "మందులు ఆర్డర్ చేయండి",
    "Book Lab Tests": "ల్యాబ్ పరీక్షలు బుక్ చేయండి",
    "Manage Insurance": "భీమా నిర్వహించండి",
    "Training & Courses": "శిక్షణ & కోర్సులు",
    "Hospitals": "ఆసుపత్రులు",
    "Blood Bank": "బ్లడ్ బ్యాంక్",
    "Organ Donation": "అవయవ దానం",
    "QR Scanner": "క్యూఆర్ స్కానర్",
    "Create ABHA Card": "ఆభా కార్డు సృష్టించండి",
    "Live Health Dashboard": "లైవ్ హెల్త్ డ్యాష్‌బోర్డ్",
    "AI Alerts": "ఏఐ హెచ్చరికలు",
    "Device Sync": "డివైస్ సింక్",
    "Telemedicine": "టెలిమెడిసిన్",
    "Video / Audio Consultation": "వీడియో / ఆడియో సంప్రదింపులు",
    "Connect with doctors instantly": "వైద్యులతో తక్షణమే కనెక్ట్ అవ్వండి",
    "Join Now": "ఇప్పుడే చేరండి",
    "Waiting Room": "వెయిటింగ్ రూమ్",
    "Patients Ahead": "రోగులు ముందు ఉన్నారు",
    "Est. 8 mins wait": "సుమారు 8 నిమిషాల నిరీక్షణ",
    "Multi-Doctor": "మల్టీ-డాక్టర్",
    "Conference": "కాన్ఫరెన్స్",
    "Connect with specialists": "నిపుణులతో కనెక్ట్ అవ్వండి",
    "Marketplace": "మార్కెట్‌ప్レーస్",
    "Medicine Delivery": "మందుల పంపిణీ",
    "Lab Booking": "ల్యాబ్ బుకింగ్",
    "Home Sample Collection": "ఇంటి వద్ద నమూనా సేకరణ",
    "Medical Equipment": "వైద్య పరికరాలు",
    "Ambulance Booking": "అంబులెన్స్ బుకింగ్",
    "Drone Delivery": "డ్రోన్ డెలివరీ",
    "Coming Soon": "త్వరలో వస్తుంది",
    "Medicolegal & Compliance": "మెడికోలీగల్ & వర్తింపు",
    "Medicolegal Support": "మెడికోలీగల్ మద్దతు",
    "Digital Consent Forms": "డిజిటల్ సమ్మతి పత్రాలు",
    "Prescription Verification": "ప్రిస్క్రిప్షన్ ధృవీకరణ",
    "Secure Health Records": "సురક્ષిత ఆరోగ్య రికార్డులు",
    "Telemedicine Compliance": "టెలిమెడిసిన్ వర్తింపు",
    "Legal Docs Vault": "లీగల్ డాక్స్ వాల్ట్",
    "ABDM Compliant": "ABDM నిబంధనలకు లోబడి",
    "HIPAA Secure": "HIPAA సురక్షితం",
    "GDPR Ready": "GDPR సిద్ధం",
    "DPDP Compliant": "DPDP నిబంధనలకు లోబడి",
    "Health Insights & Education": "ఆరోగ్య అంతర్దృష్టులు & విద్య",
    "Health Tips": "ఆరోగ్య చిట్కాలు",
    "Daily tips for a healthy life": "ఆరోగ్యకరమైన జీవితం కోసం రోజువారీ చిట్కాలు",
    "Appointment Reminders": "అపాయింట్‌మెంట్ రిమైండర్లు",
    "Never miss your appointments": "మీ అపాయింట్‌మెంట్‌లను ఎప్పటికీ కోల్పోకండి",
    "Preventive Care": "నివారణ సంరక్షణ",
    "Regular checkups for a better you": "మెరుగైన మీ కోసం రెగ్యులర్ చెకప్‌లు",
    "Chronic Disease Programs": "దీర్ఘకాలిక వ్యాధి కార్యక్రమాలు",
    "Specialized care for chronic conditions": "దీర్ఘకాలిక పరిస్థితుల కోసం ప్రత్యేక సంరక్షణ",
    "AI Health Assistant": "ఏఐ హెల్త్ అసిస్టెంట్",
    "Your smart health companion": "మీ స్మార్ట్ ఆరోగ్య సహచరుడు",
    "Home": "హోమ్",
    "Health": "ఆరోగ్యం",
    "Appointments": "నియామకాలు",
    "Records": "రికార్డులు",
    "More": "మరింత"
  },
  BN: {
    "Your Digital": "আপনার ডিজিটাল",
    "Healthcare Ecosystem": "স্বাস্থ্যসেবা ইকোসিস্টেম",
    "Book Consultation": "পরামর্শ বুক করুন",
    "Health ATM": "হেলথ এটিএম",
    "Digital Locker": "ডিজিটাল লকার",
    "Quick Access": "দ্রুত অ্যাক্সেস",
    "View All": "সব দেখুন",
    "Consult Doctor": "ডাক্তার দেখান",
    "Order Medicines": "ওষুধ অর্ডার করুন",
    "Book Lab Tests": "ল্যাব টেস্ট বুক করুন",
    "Manage Insurance": "বীমা পরিচালনা করুন",
    "Training & Courses": "প্রশিক্ষণ ও কোর্স",
    "Hospitals": "হাসপাতাল",
    "Blood Bank": "ব্লাড ব্যাংক",
    "Organ Donation": "অঙ্গদান",
    "QR Scanner": "কিউআর স্ক্যানার",
    "Create ABHA Card": "আভা কার্ড তৈরি করুন",
    "Live Health Dashboard": "লাইভ স্বাস্থ্য ড্যাশবোর্ড",
    "AI Alerts": "এআই অ্যালার্ট",
    "Device Sync": "ডিভাইস সিঙ্ক",
    "Telemedicine": "টেলিমেডিসিন",
    "Video / Audio Consultation": "ভিডিও / অডিও পরামর্শ",
    "Connect with doctors instantly": "ডাক্তারদের সাথে সাথে সাথে যোগাযোগ করুন",
    "Join Now": "এখনই যোগ দিন",
    "Waiting Room": "অপেক্ষার ঘর",
    "Patients Ahead": "রোগী আগে আছেন",
    "Est. 8 mins wait": "আনুমানিক ৮ মিনিট অপেক্ষা",
    "Multi-Doctor": "মাল্টি-ডাক্তার",
    "Conference": "কনফারেন্স",
    "Connect with specialists": "বিশেষজ্ঞদের সাথে যোগাযোগ করুন",
    "Marketplace": "মার্কেটপ্লেস",
    "Medicine Delivery": "ওষুধ সরবরাহ",
    "Lab Booking": "ল্যাব বুকিং",
    "Home Sample Collection": "হোম স্যাম্পল কালেকশন",
    "Medical Equipment": "চিকিৎসা সরঞ্জাম",
    "Ambulance Booking": "অ্যাম্বুলেন্স বুকিং",
    "Drone Delivery": "ড্রোন ডেলিভারি",
    "Coming Soon": "শীঘ্রই আসছে",
    "Medicolegal & Compliance": "মেডিকোলেগাল ও কমপ্লায়েন্স",
    "Medicolegal Support": "মেডিকোলেগাল সহায়তা",
    "Digital Consent Forms": "ডিজিটাল সম্মতি ফর্ম",
    "Prescription Verification": "প্রেসক্রিপশন যাচাইকরণ",
    "Secure Health Records": "সুরক্ষিত স্বাস্থ্য রেকর্ড",
    "Telemedicine Compliance": "টেলিমেডিসিন কমপ্লায়েন্স",
    "Legal Docs Vault": "আইনি নথি ভল্ট",
    "ABDM Compliant": "ABDM অনুগত",
    "HIPAA Secure": "HIPAA সুরক্ষিত",
    "GDPR Ready": "GDPR প্রস্তুত",
    "DPDP Compliant": "DPDP অনুগত",
    "Health Insights & Education": "স্বাস্থ্য অন্তর্দৃষ্টি ও শিক্ষা",
    "Health Tips": "স্বাস্থ্য টিপস",
    "Daily tips for a healthy life": "সুস্থ জীবনের জন্য দৈনিক টিপস",
    "Appointment Reminders": "অ্যাপয়েন্টমেন্ট অনুস্মারক",
    "Never miss your appointments": "আপনার অ্যাপয়েন্টমেন্ট মিস করবেন না",
    "Preventive Care": "প্রতিরোধমূলক যত্ন",
    "Regular checkups for a better you": "একটি ভাল আপনার জন্য নিয়মিত পরীক্ষা",
    "Chronic Disease Programs": "দীর্ঘস্থায়ী রোগ প্রোগ্রাম",
    "Specialized care for chronic conditions": "দীর্ঘস্থায়ী অবস্থার জন্য বিশেষ যত্ন",
    "AI Health Assistant": "এআই স্বাস্থ্য সহকারী",
    "Your smart health companion": "আপনার smart স্বাস্থ্য সঙ্গী",
    "Home": "হোম",
    "Health": "স্বাস্থ্য",
    "Appointments": "অ্যাপয়েন্টমেন্ট",
    "Records": "রেকর্ড",
    "More": "আরো"
  },
  MR: {
    "Your Digital": "तुमची डिजिटल",
    "Healthcare Ecosystem": "आरोग्य सेवा इकोसिस्टम",
    "Book Consultation": "सल्लामसलत बुक करा",
    "Health ATM": "हेल्थ एटीएम",
    "Digital Locker": "डिजिटल लॉकर",
    "Quick Access": "त्वरित प्रवेश",
    "View All": "सर्व पहा",
    "Consult Doctor": "डॉक्टरांचा सल्ला घ्या",
    "Order Medicines": "औषधे ऑर्डर करा",
    "Book Lab Tests": "लॅब चाचण्या बुक करा",
    "Manage Insurance": "विमा व्यवस्थापित करा",
    "Training & Courses": "प्रशिक्षण आणि अभ्यासक्रम",
    "Hospitals": "रुग्णालये",
    "Blood Bank": "ब्लड बँक",
    "Organ Donation": "अवयव दान",
    "QR Scanner": "क्यूआर स्कॅनर",
    "Create ABHA Card": "आभा कार्ड बनवा",
    "Live Health Dashboard": "लाइव्ह हेल्थ डॅशबोर्ड",
    "AI Alerts": "एआय अलर्ट",
    "Device Sync": "डिव्हाइस सिंक",
    "Telemedicine": "टेलीमेडिसिन",
    "Video / Audio Consultation": "व्हिडिओ / ऑडिओ सल्लामसलत",
    "Connect with doctors instantly": "डॉक्टरांशी त्वरित संपर्क साधा",
    "Join Now": "आता सामील व्हा",
    "Waiting Room": "प्रतिक्षा कक्ष",
    "Patients Ahead": "रुग्ण पुढे आहेत",
    "Est. 8 mins wait": "अंदाजे ८ मिनिटे प्रतीक्षा",
    "Multi-Doctor": "मल्टी-डॉक्टर",
    "Conference": "परिषद",
    "Connect with specialists": "तज्ञांशी संपर्क साधा",
    "Marketplace": "मार्केटप्लेस",
    "Medicine Delivery": "औषध वितरण",
    "Lab Booking": "लॅब बुकिंग",
    "Home Sample Collection": "घरी नमुना संकलन",
    "Medical Equipment": "वैद्यकीय उपकरणे",
    "Ambulance Booking": "अँबुलन्स बुकिंग",
    "Drone Delivery": "ड्रोन डिलिव्हरी",
    "Coming Soon": "लवकरच येत आहे",
    "Medicolegal & Compliance": "मेडिकोलीगल आणि अनुपालन",
    "Medicolegal Support": "मेडिकोलीगल समर्थन",
    "Digital Consent Forms": "डिजिटल संमती फॉर्म",
    "Prescription Verification": "प्रिस्क्रिप्शन पडताळणी",
    "Secure Health Records": "सुरक्षित आरोग्य रेकॉर्ड",
    "Telemedicine Compliance": "टेलीमेडिसिन अनुपालन",
    "Legal Docs Vault": "कायदेशीर दस्तऐवज वॉल्ट",
    "ABDM Compliant": "ABDM सुसंगत",
    "HIPAA Secure": "HIPAA सुरक्षित",
    "GDPR Ready": "GDPR तयार",
    "DPDP Compliant": "DPDP सुसंगत",
    "Health Insights & Education": "आरोग्य अंतर्दृष्टी आणि शिक्षण",
    "Health Tips": "आरोग्य टिप्स",
    "Daily tips for a healthy life": "निरोगी आयुष्यासाठी रोजच्या टिप्स",
    "Appointment Reminders": "अपॉइंटमेंट स्मरणपत्रे",
    "Never miss your appointments": "तुमची अपॉइंटमेंट कधीही चुकवू नका",
    "Preventive Care": "प्रतिबंधात्मक काळजी",
    "Regular checkups for a better you": "चांगल्या आरोग्यासाठी नियमित तपासणी",
    "Chronic Disease Programs": "तीव्र रोग कार्यक्रम",
    "Specialized care for chronic conditions": "तीव्र आजारांसाठी विशेष काळजी",
    "AI Health Assistant": "एआय आरोग्य सहाय्यक",
    "Your smart health companion": "तुमचा स्मार्ट आरोग्य सोबती",
    "Home": "होम",
    "Health": "आरोग्य",
    "Appointments": "अपॉइंटमेंट",
    "Records": "रेकॉर्ड",
    "More": "अधिक"
  },
  GU: {
    "Your Digital": "તમારું ડિજિટલ",
    "Healthcare Ecosystem": "હેલ્થકેર ઇકોસિસ્ટમ",
    "Book Consultation": "પરામર્શ બુક કરો",
    "Health ATM": "હેલ્થ એટીએમ",
    "Digital Locker": "ડિજિટલ લોકર",
    "Quick Access": "ઝડપી પ્રવેશ",
    "View All": "બધું જુઓ",
    "Consult Doctor": "ડોક્ટરની સલાહ",
    "Order Medicines": "દવાઓ ઓર્ડર કરો",
    "Book Lab Tests": "લેબ ટેસ્ટ બુક કરો",
    "Manage Insurance": "વીમો સંચાલિત કરો",
    "Training & Courses": "તાલીમ અને અભ્યાસક્રમો",
    "Hospitals": "હોસ્પિટલો",
    "Blood Bank": "બ્લડ બેંક",
    "Organ Donation": "અંગ દાન",
    "QR Scanner": "ક્યૂઆર સ્કેનર",
    "Create ABHA Card": "આભા કાર્ડ બનાવો",
    "Live Health Dashboard": "લાઇવ હેલ્થ ડેશબોર્ડ",
    "AI Alerts": "એઆઈ એલર્ટ",
    "Device Sync": "ડિવાઇસ સિંક",
    "Telemedicine": "ટેલીમેડિસિન",
    "Video / Audio Consultation": "વિડિઓ / ઓડિયો પરામર્શ",
    "Connect with doctors instantly": "ડોકટરો સાથે તરત જ જોડાઓ",
    "Join Now": "હમણાં જોડાઓ",
    "Waiting Room": "પ્રતીક્ષા ખંડ",
    "Patients Ahead": "દર્દીઓ આગળ છે",
    "Est. 8 mins wait": "આશરે ૮ મિનિટ પ્રતીક્ષા",
    "Multi-Doctor": "મલ્ટી-ડોક્ટર",
    "Conference": "કોન્ફરન્સ",
    "Connect with specialists": "નિષ્ણાતો સાથે જોડાઓ",
    "Marketplace": "માર્કેટપ્લેસ",
    "Medicine Delivery": "દવા વિતરણ",
    "Lab Booking": "લેબ બુકિંગ",
    "Home Sample Collection": "ઘરે સેમ્પલ કલેક્શન",
    "Medical Equipment": "તબીબી સાધનો",
    "Ambulance Booking": "એમ્બ્યુલન્સ બુકિંગ",
    "Drone Delivery": "ડ્રોન ડિલિવરી",
    "Coming Soon": "ટૂંક સમયમાં આવી રહ્યું છે",
    "Medicolegal & Compliance": "મેડિકોલીગલ અને અનુપાલન",
    "Medicolegal Support": "મેડિકોલીગલ સપોર્ટ",
    "Digital Consent Forms": "ડિજิตલ સંમતિ પત્રો",
    "Prescription Verification": "પ્રિસ્ક્રિપ્શન ચકાસણી",
    "Secure Health Records": "સુરક્ષિત આરોગ્ય રેકોર્ડ્સ",
    "Telemedicine Compliance": "ટેલીમેડિસિન અનુપาลન",
    "Legal Docs Vault": "કાનૂની દસ્તાવેજો વોલ્ટ",
    "ABDM Compliant": "ABDM સુસંગત",
    "HIPAA Secure": "HIPAA સુરક્ષित",
    "GDPR Ready": "GDPR તૈયાર",
    "DPDP Compliant": "DPDP સુસંગત",
    "Health Insights & Education": "આરોગ્ય આંતરદૃષ્ટિ અને શિક્ષણ",
    "Health Tips": "આરોગ્ય ટિપ્સ",
    "Daily tips for a healthy life": "સ્વસ્થ જીવન માટે દૈનિક ટિપ્સ",
    "Appointment Reminders": "એપોઇન્ટમેન્ટ રીમાઇન્ડર્સ",
    "Never miss your appointments": "તમારી એપોઇન્ટમેન્ટ ક્યારેય ચૂકશો નહીં",
    "Preventive Care": "નિવારક સંભાળ",
    "Regular checkups for a better you": "વધુ સારા સ્વાસ્થ્ય માટે નિયમિત તપાસ",
    "Chronic Disease Programs": "ક્રોનિક રોગ કાર્યક્રમો",
    "Specialized care for chronic conditions": "ક્રોનિક રોગો માટે ખાસ કાળજી",
    "AI Health Assistant": "એઆઈ આરોગ્ય સહાયક",
    "Your smart health companion": "તમારો સ્માર્ટ આરોગ્ય સાથી",
    "Home": "હોમ",
    "Health": "આરોગ્ય",
    "Appointments": "એપોઇન્ટમેન્ટ",
    "Records": "રેકોર્ડ્સ",
    "More": "વધુ"
  },
  KN: {
    "Your Digital": "ನಿಮ್ಮ ಡಿಜಿಟಲ್",
    "Healthcare Ecosystem": "ಆರೋಗ್ಯ ರಕ್ಷಣೆ ಪರಿಸರ ವ್ಯವಸ್ಥೆ",
    "Book Consultation": "ಸಮಾಲೋಚನೆ ಬುಕ್ ಮಾಡಿ",
    "Health ATM": "ಹೆಲ್ತ್ ಎಟಿಎಂ",
    "Digital Locker": "ಡಿಜಿಟಲ್ ಲಾಕರ್",
    "Quick Access": "ತ್ವರಿತ ಪ್ರವೇಶ",
    "View All": "ಎಲ್ಲವನ್ನೂ ವೀಕ್ಷಿಸಿ",
    "Consult Doctor": "ವೈದ್ಯರನ್ನು ಸಂಪರ್ಕಿಸಿ",
    "Order Medicines": "ಔಷಧಿಗಳನ್ನು ಆರ್ಡರ್ ಮಾಡಿ",
    "Book Lab Tests": "ಲ್ಯಾಬ್ ಪರೀಕ್ಷೆಗಳನ್ನು ಬುಕ್ ಮಾಡಿ",
    "Manage Insurance": "ವಿಮೆಯನ್ನು ನಿರ್ವಹಿಸಿ",
    "Training & Courses": "ತರಬೇತಿ ಮತ್ತು ಕೋರ್ಸ್‌ಗಳು",
    "Hospitals": "ಆಸ್ಪತ್ರೆಗಳು",
    "Blood Bank": "ರಕ್ತನಿಧಿ",
    "Organ Donation": "ಅಂಗದಾನ",
    "QR Scanner": "ಕ್ಯೂಆರ್ ಸ್ಕ್ಯಾನರ್",
    "Create ABHA Card": "ಆಭಾ ಕಾರ್ಡ್ ರಚಿಸಿ",
    "Live Health Dashboard": "ಲೈವ್ ಹೆಲ್ತ್ ಡ್ಯಾಶ್‌ಬೋರ್ಡ್",
    "AI Alerts": "ಎಐ ಎಚ್ಚರಿಕೆಗಳು",
    "Device Sync": "ಡಿವೈಸ್ ಸಿಂಕ್",
    "Telemedicine": "ಟೆಲಿಮೆಡಿಸಿನ್",
    "Video / Audio Consultation": "ವಿಡಿಯೋ / ಆಡಿಯೋ ಸಮಾಲೋಚನೆ",
    "Connect with doctors instantly": "ವೈದ್ಯರೊಂದಿಗೆ ತಕ್ಷಣ ಸಂಪರ್ಕ ಸಾಧಿಸಿ",
    "Join Now": "ಈಗಲೇ ಸೇರಿಕೊಳ್ಳಿ",
    "Waiting Room": "ಕಾಯುವ ಕೊಠಡಿ",
    "Patients Ahead": "ರೋಗಿಗಳು ಮುಂದೆ ಇದ್ದಾರೆ",
    "Est. 8 mins wait": "ಅಂದಾಜು 8 ನಿಮಿಷ ಕಾಯುವಿಕೆ",
    "Multi-Doctor": "ಮಲ್ಟಿ-ಡಾಕ್ಟರ್",
    "Conference": "ಕಾನ್ಫರೆನ್ಸ್",
    "Connect with specialists": "ತಜ್ಞರೊಂದಿಗೆ ಸಂಪರ್ಕ ಸಾಧಿಸಿ",
    "Marketplace": "ಮಾರುಕಟ್ಟೆ",
    "Medicine Delivery": "ಔಷಧಿ ವಿತರಣೆ",
    "Lab Booking": "ಲ್ಯಾಬ್ ಬುಕಿಂಗ್",
    "Home Sample Collection": "ಮನೆಯಲ್ಲಿ ಮಾದರಿ ಸಂಗ್ರಹಣೆ",
    "Medical Equipment": "ವೈದ್ಯಕೀಯ ಉಪಕರಣಗಳು",
    "Ambulance Booking": "ಆಂಬ್ಯುಲೆನ್ಸ್ ಬುಕಿಂಗ್",
    "Drone Delivery": "ಡ್ರೋನ್ ಡೆಲಿವರಿ",
    "Coming Soon": "ಶೀಘ್ರದಲ್ಲೇ ಬರಲಿದೆ",
    "Medicolegal & Compliance": "ಮೆಡಿಕೋಲೀಗಲ್ ಮತ್ತು ಅನುಸರಣೆ",
    "Medicolegal Support": "ಮೆಡಿಕೋಲೀಗಲ್ ಬೆಂಬಲ",
    "Digital Consent Forms": "ಡಿಜಿಟಲ್ ಒಪ್ಪಿಗೆ ಪತ್ರಗಳು",
    "Prescription Verification": "ಪ್ರಿಸ್ಕ್ರಿಪ್ಷನ್ ಪರಿಶೀಲನೆ",
    "Secure Health Records": "ಸುರಕ್ಷಿತ ಆರೋಗ್ಯ ದಾಖಲೆಗಳು",
    "Telemedicine Compliance": "ಟೆಲಿಮೆಡಿಸಿನ್ ಅನುಸರಣೆ",
    "Legal Docs Vault": "ಕಾನೂನು ದಾಖಲೆಗಳ ವಾಲ್ಟ್",
    "ABDM Compliant": "ABDM ಕಂಪ್ಲైಂಟ್",
    "HIPAA Secure": "HIPAA ಸುರಕ್ಷಿತ",
    "GDPR Ready": "GDPR ಸಿದ್ಧ",
    "DPDP Compliant": "DPDP ಕಂಪ್ಲైಂಟ್",
    "Health Insights & Education": "ಆರೋಗ್ಯ ಒಳನೋಟಗಳು ಮತ್ತು ಶಿಕ್ಷಣ",
    "Health Tips": "ಆರೋಗ್ಯ ಸಲಹೆಗಳು",
    "Daily tips for a healthy life": "ಆರೋಗ್ಯಕರ ಜೀವನಕ್ಕಾಗಿ ದೈನಂದิน ಸಲಹೆಗಳು",
    "Appointment Reminders": "ಅಪಾಯಿಂಟ್‌ಮೆಂಟ್ ಜ್ಞಾಪನೆಗಳು",
    "Never miss your appointments": "ನಿಮ್ಮ ಅಪಾಯಿಂಟ್‌ಮೆಂಟ್‌ಗಳನ್ನು ಎಂದಿಗೂ ತಪ್ಪಿಸಬೇಡಿ",
    "Preventive Care": "ತಡೆಗಟ್ಟುವ ಆರೈಕೆ",
    "Regular checkups for a better you": "ಉತ್ತಮ ಆರೋಗ್ಯಕ್ಕಾಗಿ ನಿಯಮಿತ ತಪಾಸಣೆ",
    "Chronic Disease Programs": "ದೀರ್ಘಕಾಲದ ಕಾಯಿಲೆ ಕಾರ್ಯಕ್ರಮಗಳು",
    "Specialized care for chronic conditions": "ದೀರ್ಘಕಾಲದ ಕಾಯಿಲೆಗಳಿಗೆ ವಿಶೇಷ ಆರೈಕೆ",
    "AI Health Assistant": "ಎಐ ಆರೋಗ್ಯ ಸಹಾಯಕ",
    "Your smart health companion": "ನಿಮ್ಮ ಸ್ಮಾರ್ಟ್ ಆರೋಗ್ಯ ಒಡನಾಡಿ",
    "Home": "ಹೋಮ್",
    "Health": "ಆರೋಗ್ಯ",
    "Appointments": "ನೇಮಕಾতিಗಳು",
    "Records": "ದಾಖಲೆಗಳು",
    "More": "ಇನ್ನಷ್ಟು"
  }
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguageState] = useState<LanguageCode>('EN');

  useEffect(() => {
    try {
      const state = JSON.parse(localStorage.getItem('setu_state') || '{}');
      if (state.language) {
        setLanguageState(state.language);
      }
    } catch (e) {
      console.error(e);
    }
  }, []);

  const setLanguage = (lang: LanguageCode) => {
    setLanguageState(lang);
    try {
      const state = JSON.parse(localStorage.getItem('setu_state') || '{}');
      state.language = lang;
      localStorage.setItem('setu_state', JSON.stringify(state));
    } catch (e) {
      console.error(e);
    }
  };

  const t = (key: string): string => {
    const table = translations[language];
    if (table && table[key]) {
      return table[key];
    }
    return key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}
