'use client';

import React, { createContext, useContext, useEffect, useState } from 'react';

export type LanguageCode = 'EN' | 'HI' | 'TA' | 'TE' | 'BN' | 'MR' | 'GU' | 'KN';

interface LanguageContextType {
  language: LanguageCode;
  setLanguage: (lang: LanguageCode) => void;
  t: (key: string) => string;
}

const translations: Record<LanguageCode, Record<string, string>> = {
  EN: {},
  HI: {
    "Your Digital": "आपका डिजिटल",
    "Healthcare Ecosystem": "स्वास्थ्य सेवा पारिस्थितिकी तंत्र",
    "Book Consultation": "परामर्श बुक करें",
    "Book Doctor": "डॉक्टर बुक करें",
    "Health ATM": "हेल्थ एटीएम",
    "Digital Locker": "डिजिटल लॉकर",
    "Health Locker": "हेल्थ लॉकर",
    "Quick Access": "त्वरित पहुँच",
    "View All": "सभी देखें",
    "Consult Doctor": "डॉक्टर से परामर्श",
    "Order Medicines": "दवाएं ऑर्डर करें",
    "Book Lab Tests": "लैब टेस्ट बुक करें",
    "Manage Insurance": "बीमा प्रबंधित करें",
    "Training & Courses": "प्रशिक्षण और पाठ्यक्रम",
    "Hospitals": "अस्पताल",
    "Blood Bank": "ब्लड बैंक",
    "Organ Donation": "अंग दान",
    "QR Scanner": "क्यूआर स्कैनर",
    "Create ABHA Card": "आभा कार्ड बनाएं",
    "Live Health Dashboard": "लाइव्ह स्वास्थ्य डैशबोर्ड",
    "AI Alerts": "एआई अलर्ट",
    "Device Sync": "डिवाइस सिंक",
    "Telemedicine": "टेलीमेडिसिन",
    "Video / Audio Consultation": "वीडियो / ऑडियो परामर्श",
    "Connect with doctors instantly": "डॉक्टरों से तुरंत जुड़ें",
    "Join Now": "अभी जुड़ें",
    "Waiting Room": "प्रतीक्षा कक्ष",
    "Patients Ahead": "मरीज आगे हैं",
    "Est. 8 mins wait": "अनुमानित 8 मिनट प्रतीक्षा",
    "Multi-Doctor": "बहु-डॉक्टर",
    "Conference": "कॉन्फ्रेंस",
    "Connect with specialists": "विशेषज्ञों से जुड़ें",
    "Marketplace": "मार्केटप्लेस",
    "Medicine Delivery": "दवा वितरण",
    "Lab Booking": "लैब बुकिंग",
    "Home Sample Collection": "गृह नमूना संग्रह",
    "Medical Equipment": "चिकित्सा उपकरण",
    "Ambulance Booking": "एम्बुलेंस बुकिंग",
    "Drone Delivery": "ड्रोन डिलीवरी",
    "Coming Soon": "जल्द आ रहा है",
    "Medicolegal & Compliance": "मेडिकोलीगल और अनुपालन",
    "Medicolegal Support": "मेडिकोलीगल सहायता",
    "Digital Consent Forms": "डिजिटल सहमति पत्र",
    "Prescription Verification": "पर्चे का सत्यापन",
    "Secure Health Records": "सुरक्षित स्वास्थ्य रिकॉर्ड",
    "Telemedicine Compliance": "टेलीमेडिसिन अनुपालन",
    "Legal Docs Vault": "कानूनी दस्तावेज वॉल्ट",
    "ABDM Compliant": "ABDM अनुपालन",
    "HIPAA Secure": "HIPAA सुरक्षित",
    "GDPR Ready": "GDPR तैयार",
    "DPDP Compliant": "DPDP अनुपालन",
    "Health Insights & Education": "स्वास्थ्य अंतर्दृष्टि और शिक्षा",
    "Health Tips": "स्वास्थ्य युक्तियाँ",
    "Daily tips for a healthy life": "स्वस्थ जीवन के लिए दैनिक सुझाव",
    "Appointment Reminders": "अपॉइंटमेंट अनुस्मारक",
    "Never miss your appointments": "अपने अपॉइंटमेंट कभी न चूकें",
    "Preventive Care": "निवारक देखभाल",
    "Regular checkups for a better you": "बेहतर स्वास्थ्य के लिए नियमित जांच",
    "Chronic Disease Programs": "क्रोनिक बीमारी कार्यक्रम",
    "Specialized care for chronic conditions": "क्रोनिक स्थितियों के लिए विशेष देखभाल",
    "AI Health Assistant": "एआई स्वास्थ्य सहायक",
    "Your smart health companion": "आपका स्मार्ट स्वास्थ्य साथी",
    "Home": "होम",
    "Health": "स्वास्थ्य",
    "Appointments": "अपॉइंटमेंट",
    "Records": "रिकॉर्ड",
    "More": "अधिक",
    "Link Hospital Records": "अस्पताल रिकॉर्ड लिंक करें",
    "Share Records (Consent)": "रिकॉर्ड साझा करें (सहमति)",
    "Scan & Share (OPD)": "स्कैन और साझा (ओपीडी)",
    "Search Doctors & Book": "डॉक्टर खोजें और बुक करें",
    "Insurance Claims": "बीमा दावे (क्लेम्स)",
    "Doctor Registry (HPR)": "डॉक्टर रजिस्ट्री (HPR)",
    "Developer Sandbox Tests": "डेवलपर सैंडबॉक्स टेस्ट",
    "Interoperable Doctor Consultations": "इंटरऑपरेबल डॉक्टर परामर्श",
    "Redesigned booking workflow linking care contexts and clinic registry tokens under NHA specs.": "NHA विनिर्देशों के तहत देखभाल संदर्भों और क्लिनिक रजिस्ट्री टोकन को जोड़ने वाला नया बुकिंग वर्कफ़्लो।",
    "Start Booking": "बुकिंग शुरू करें",
    "Token Registry History": "टोकन रजिस्ट्री इतिहास",
    "Please complete preceding steps to unlock.": "अनलॉक करने के लिए कृपया पिछले चरणों को पूरा करें।",
    "Allopathy": "एलोपैथी",
    "Dental Care": "दंत चिकित्सा",
    "Homeopathy": "होम्योपैथी",
    "Ayurveda": "आयुर्वेद",
    "Unani": "यूनानी",
    "Physiotherapy": "फिजियोथेरेपी",
    "Mental Health & Psychology": "मानसिक स्वास्थ्य और मनोविज्ञान",
    "Dentist": "दंत चिकित्सक",
    "System": "सिस्टम",
    "Speciality": "विशेषता",
    "Doctor": "डॉक्टर",
    "Doctors": "डॉक्टर",
    "Doctors Available": "डॉक्टर उपलब्ध",
    "Facility": "सुविधा",
    "Schedule": "अनुसूची",
    "Payment": "भुगतान",
    "OPD Token": "ओपीडी टोकन",
    "ABHA Link": "आभा लिंक",
    "Meet": "परामर्श",
    "Step 1: Select Medical System": "चरण 1: चिकित्सा प्रणाली का चयन करें",
    "Select the clinical standard or traditional medicine approach for your consultation.": "अपने परामर्श के लिए नैदानिक मानक या पारंपरिक चिकित्सा पद्धति का चयन करें।",
    "Step 2: Select Specialty / Organ System": "चरण 2: विशेषता / अंग प्रणाली का चयन करें",
    "Choose the specific health category or clinical specialty fields.": "विशिष्ट स्वास्थ्य श्रेणी या नैदानिक विशेषता क्षेत्रों का चयन करें।",
    "Step 3: Choose Registered Practitioner": "चरण 3: पंजीकृत चिकित्सक चुनें",
    "Verify practitioner HPR licenses and digital seals before scheduling.": "निर्धारण से पहले चिकित्सक के HPR लाइसेंस और डिजिटल मुहरों को सत्यापित करें।",
    "Step 4: Select Clinical Care Facility": "चरण 4: नैदानिक ​​देखभाल सुविधा का चयन करें",
    "Verify the hospital/clinic facility details registered on the HFR node.": "HFR नोड पर पंजीकृत अस्पताल/क्लिनिक सुविधा विवरण सत्यापित करें।",
    "Step 5: Pick Slot & Outline Symptoms": "चरण 5: स्लॉट चुनें और लक्षणों की रूपरेखा तैयार करें",
    "Choose your time block and describe symptoms to initialize the care context.": "अपना समय ब्लॉक चुनें और देखभाल संदर्भ को प्रारंभ करने के लिए लक्षणों का वर्णन करें।",
    "Step 6: Secure Consultation Checkout": "चरण 6: सुरक्षित परामर्श चेकआउट",
    "Verify checkout billing breakup and select simulated payment gateway.": "चेकआउट बिलिंग ब्रेकअप को सत्यापित करें और सिमुलेटेड पेमेंट गेटवे का चयन करें।",


    "Start Booking Flow": "बुकिंग फ्लो शुरू करें",
    "Start Booking Wizard": "बुकिंग विज़ार्ड शुरू करें",
    "Direct Doctor Search": "सीधा डॉक्टर खोजें",
    "Search Doctors by Name or Speciality...": "डॉक्टरों को नाम या विशेषता से खोजें...",
    "Select Medical System First": "पहले चिकित्सा प्रणाली का चयन करें",
    "No doctors found matching search.": "खोज से मेल खाने वाला कोई डॉक्टर नहीं मिला।",
    "No doctors currently available in the database for this role.": "इस भूमिका के लिए वर्तमान में डेटाबेस में कोई डॉक्टर उपलब्ध नहीं है।",
    "Please enter a valid ABHA Address (e.g. user@abdm)": "कृपया एक वैध आभा पता दर्ज करें (जैसे user@abdm)",
    "Verification OTP sent.": "सत्यापन ओटीपी भेज दिया गया है।",
    "ABHA Linked successfully!": "आभा सफलतापूर्वक लिंक किया गया!",
    "Please enter verification OTP.": "कृपया सत्यापन ओटीपी दर्ज करें।",
    "Invalid OTP. Please use 123456.": "अवैध ओटीपी। कृपया 123456 का उपयोग करें.",
    "Scan QR for Spot Booking": "स्पॉट बुकिंग के लिए क्यूआर स्कैन करें",
    "Explore specialties": "विशेषताओं का अन्वेषण करें",
    "Back": "पीछे",
    "System:": "सिस्टम:",
    "Fee:": "शुल्क:",
    "Rating:": "रेटिंग:",
    "Active Consultations": "सक्रिय परामर्श",
    "No active scheduled appointments.": "कोई सक्रिय निर्धारित अपॉइंटमेंट नहीं है।",
    "OPD Token History": "ओपीडी टोकन इतिहास",
    "Doctors Manager": "डॉक्टर प्रबंधक",
    "Registered Practitioners": "पंजीकृत चिकित्सक",
    "Register Doctor": "डॉक्टर का पंजीकरण करें",
    "Doctor Name": "डॉक्टर का नाम",
    "Medical System": "चिकित्सा प्रणाली",
    "Speciality Category": "विशेषता श्रेणी",
    "Specialist Role / Title": "विशेषज्ञ भूमिका / शीर्षक",
    "Degrees / Qualifications": "डिग्रियां / योग्यताएं",
    "Experience Text": "अनुभव पाठ",
    "Consultation Fee (₹)": "परामर्श शुल्क (₹)",
    "Default Rating (1-5)": "डिफ़ॉल्ट रेटिंग (1-5)",
    "Hospital / Clinic Name": "अस्पताल / क्लिनिक का नाम",
    "Hospital HFR Node ID": "अस्पताल HFR नोड आईडी",
    "License / HPR Certificate ID": "लाइसेंस / HPR प्रमाणपत्र आईडी",
    "Practitioner Photo URL (Optional)": "चिकित्सक फोटो यूआरएल (वैकल्पिक)",
    "Practitioner Biography / Description": "चिकित्सक जीवनी / विवरण",
    "Edit Doctor Registration": "डॉक्टर पंजीकरण संपादित करें",
    "Register New Doctor": "नया डॉक्टर पंजीकृत करें",
    "Cancel": "रद्द करें",
    "Save Changes": "बदलाव सहेजें",
    "This facility is fully verified under the NHA Health Facility Registry (HFR). Choosing this location allows ABHA fast-track OPD token generation and instant record linking.": "यह सुविधा NHA स्वास्थ्य सुविधा रजिस्ट्री (HFR) के तहत पूरी तरह से सत्यापित है। इस स्थान को चुनने से आभा त्वरित ओपीडी टोकन जनरेशन और तत्काल रिकॉर्ड लिंकिंग की अनुमति मिलती है।",
    "Timings:": "समय:",
    "Days:": "दिन:",
    "Confirm Location": "स्थान की पुष्टि करें",
    "Clinic": "क्लिनिक",
    "Clinic:": "क्लिनिक:",
    "Select Date": "तारीख चुनें",
    "Select Time Slot": "समय स्लॉट चुनें",
    "Preferred Consult Mode": "पसंदीदा परामर्श मोड",
    "Video Consultation (Virtual Room)": "वीडियो परामर्श (आभासी कमरा)",
    "Audio Call Consultation": "ऑडियो कॉल परामर्श",
    "In-Clinic OPD Appointment": "क्लिनिक में ओपीडी अपॉइंटमेंट",
    "Describe Symptoms / Medical Concerns": "लक्षणों / चिकित्सा संबंधी चिंताओं का वर्णन करें",
    "e.g. Coughing, body fatigue, mild fever since yesterday": "जैसे कि कल से खांसी, बदन दर्द, हल्का बुखार",
    "Proceed to Checkout": "चेकआउट के लिए आगे बढ़ें",
    "Billing Summary": "बिलिंग सारांश",
    "Consultation Fee": "परामर्श शुल्क",
    "Convenience Fee (Health locker support)": "सुविधा शुल्क (स्वास्थ्य लॉकर सहायता)",
    "Total Billable Amount": "कुल देय राशि",
    "Secure end-to-end NHA certified UHI checkout flow.": "सुरक्षित एंड-टू-एंड एनएचए प्रमाणित यूएचआई चेकआउट प्रवाह।",
    "Payment Settlement Method": "भुगतान निपटान विधि",
    "UPI (Instant Check-in Settlement)": "यूपीआई (त्वरित चेक-इन निपटान)",
    "Credit / Debit Card": "क्रेडिट / डेबिट कार्ड",
    "ABHA Health Wallet Balance": "आभा स्वास्थ्य वॉलेट बैलेंस",
    "Pay & Issue OPD Token": "भुगतान करें और ओपीडी टोकन जारी करें",
    "Secured by NHA gateway sandbox payment processor.": "एनएचए गेटवे सैंडबॉक्स भुगतान प्रोसेसर द्वारा सुरक्षित।",
    "NATIONAL HEALTH AUTHORITY": "राष्ट्रीय स्वास्थ्य प्राधिकरण",
    "OPD TICKET SLIP": "ओपीडी टिकट पर्ची",
    "QUEUE CODE": "कतार कोड",
    "PAID & VERIFIED": "भुगतान किया गया और सत्यापित",
    "Practitioner:": "चिकित्सक:",
    "Facility:": "सुविधा:",
    "Schedule:": "अनुसूची:",
    "Link Appointment to ABHA": "अपॉइंटमेंट को आभा से लिंक करें",
    "To proceed to the consultation room, you must link this appointment with your Ayushman Bharat Health Account (ABHA) to securely transmit and retrieve EHR data.": "परामर्श कक्ष में आगे बढ़ने के लिए, आपको ईएचआर डेटा को सुरक्षित रूप से प्रसारित और पुनः प्राप्त करने के लिए इस अपॉइंटमेंट को अपने आयुष्मान भारत स्वास्थ्य खाते (आभा) से लिंक करना होगा।",
    "Link ABHA Profile & Continue": "आभा प्रोफाइल लिंक करें और जारी रखें",
    "Patient ABHA Context Details": "मरीज आभा संदर्भ विवरण",
    "Patient Name": "मरीज का नाम",
    "ABHA Address (Health ID)": "आभा पता (स्वास्थ्य आईडी)",
    "Discovering Contexts...": "संदर्भों की खोज की जा रही है...",
    "Verify & Discover Care Contexts": "देखभाल संदर्भों को सत्यापित और खोजें",
    "Enter the 6-digit verification OTP (Enter 123456 for testing):": "6-अंकीय सत्यापन ओटीपी दर्ज करें (परीक्षण के लिए 123456 दर्ज करें):",
    "Confirm": "पुष्टि करें",
    "Care Context Linked!": "देखभाल संदर्भ लिंक हो गया!",
    "Join Consultation Room": "परामर्श कक्ष में शामिल हों",
    "ABDM Gateway Transaction Logs": "ABDM गेटवे लेनदेन लॉग",
    "Professional:": "पेशेवर:",
    "OPD Token:": "ओपीडी टोकन:",
    "Initializing Encrypted Video Node...": "एन्क्रिप्टेड वीडियो नोड प्रारंभ किया जा रहा है...",
    "Live Connection Secured": "लाइव कनेक्शन सुरक्षित",
    "Hide Linked Prescription": "लिंक किया हुआ पर्चा छिपाएं",
    "View FHIR Prescription": "FHIR पर्चा देखें",
    "Telehealth Desk": "टेलीहेल्थ डेस्क",
    "Describe symptoms or ask questions...": "लक्षणों का वर्णन करें या प्रश्न पूछें...",
    "Digitally Signed FHIR MedicationRequest Bundle": "डिजिटल रूप से हस्ताक्षरित FHIR मेडिकेशनरिक्वेस्ट बंडल",
    "Practitioner Metadata": "चिकित्सक मेटाडेटा",
    "Name:": "नाम:",
    "License No:": "लाइसेंस संख्या:",
    "HFR Node:": "HFR नोड:",
    "Prescribed Pharmacotherapy": "निर्धारित फार्माकोथेरेपी",
    "Medication:": "दवा:",
    "Dosage:": "खुराक:",
    "Status:": "स्थिति:",
    "Verified Practitioner": "सत्यापित चिकित्सक",
    "Select Professional": "चिकित्सक चुनें",
    "ABDM Settings": "ABDM सेटिंग्स",
    "ABDM Health Tests": "ABDM स्वास्थ्य परीक्षण",
    "Products Manager": "उत्पाद प्रबंधक",
    "Policies Manager": "नीति प्रबंधक",
    "Lab Tests Manager": "लैब परीक्षण प्रबंधक",
    "Security Logs": "सुरक्षा लॉग",
    "Sign Out": "साइन आउट",
    "Login": "प्रवेश",
    "Create ABHA": "नया आभा बनाएं",
    "Find ABHA": "आभा विवरण खोजें",
    "Get Started": "शुरू करें",
    "Preferred": "अनुशंसित",
    "Select Login Method": "प्रवेश का माध्यम चुनें",
    "Select Registration Method": "नया पंजीकरण माध्यम चुनें",
    "Back to Menu": "मुख्य मेनू",
    "Mobile OTP": "मोबाइल ओटीपी",
    "Aadhaar": "आधार",
    "ABHA ID": "आभा संख्या/पता",
    "Driving License": "ड्राइविंग लाइसेंस",
    "Select Language": "भाषा चुनें",
    "National Health Gateway Portal": "राष्ट्रीय स्वास्थ्य गेटवे पोर्टल",
    "Access clinical records, UHI consults, and link care contexts using secure OTP.": "सुरक्षित ओटीपी का उपयोग करके नैदानिक रिकॉर्ड, यूएचआई परामर्श तक पहुंचें और देखभाल संदर्भों को लिंक करें।",
    "Digital Health Portal": "डिजिटल स्वास्थ्य पोर्टल",
    "Login via Mobile Number": "मोबाइल नंबर द्वारा प्रवेश",
    "Login using linked mobile OTP": "लिंक किए गए मोबाइल ओटीपी का उपयोग करके प्रवेश करें",
    "Login via Aadhaar": "आधार द्वारा प्रवेश",
    "Aadhaar OTP authentication": "आधार ओटीपी सत्यापन",
    "Login via ABHA Number / Address": "आभा संख्या / पता द्वारा प्रवेश",
    "Enter 14-digit ABHA or address (@sbx)": "14-अंकीय आभा या पता (@sbx) दर्ज करें",
    "Choose how you want to log in to your digital health card profile.": "अपने डिजिटल हेल्थ कार्ड प्रोफाइल में प्रवेश करने का माध्यम चुनें।",
    "Select ABHA Creation Method": "आभा बनाने का माध्यम चुनें",
    "Choose the document to register and generate a new ABHA identity.": "नया आभा पहचान बनाने के लिए दस्तावेज चुनें।",
    "Create via Aadhaar": "आधार द्वारा बनाएं",
    "Instant ABHA Card using Aadhaar OTP": "आधार ओटीपी का उपयोग करके तुरंत आभा कार्ड बनाएं",
    "Create via Driving License": "ड्राइविंग लाइसेंस द्वारा बनाएं",
    "Enrollment using Driving License ID": "ड्राइविंग लाइसेंस आईडी का उपयोग करके पंजीकरण",
    "Retrieve your registered ABHA details:": "अपने पंजीकृत आभा विवरण प्राप्त करें:",
    "Forgot your ABHA details? Retrieve them using registered mobile.": "आभा विवरण भूल गए? पंजीकृत मोबाइल का उपयोग करके प्राप्त करें।",
    "Registered Phone": "पंजीकृत फोन",
    "10-Digit Mobile Number": "10-अंकीय मोबाइल नंबर",
    "Find My ABHA Details": "मेरा आभा विवरण खोजें",
    "Send DL Verification OTP": "ड्राइविंग लाइसेंस ओटीपी भेजें",
    "Send Gateway Verification OTP": "गेटवे सत्यापन ओटीपी भेजें",
    "Send OTP": "ओटीपी भेजें",
    "Edit Mobile": "मोबाइल बदलें",
    "Edit Aadhaar": "आधार बदलें",
    "Edit ABHA": "आभा बदलें",
    "Verify & Continue": "सत्यापित करें और आगे बढ़ें",
    "Verify & Proceed": "सत्यापित करें और आगे बढ़ें",
    "Select a method to log in to your profile:": "अपने प्रोफाइल में लॉगिन करने का माध्यम चुनें:",
    "Select a registration method below:": "नीचे दिए गए पंजीकरण माध्यमों में से चुनें:",
    "Retrieve your registered ABHA details": "पंजीकृत आभा विवरण पुनः प्राप्त करें",
    "Authentication via Mobile OTP": "मोबाइल ओटीपी द्वारा सत्यापन",
    "Aadhaar Secure Authentication": "आधार सुरक्षित सत्यापन",
    "ABHA Profile Login": "आभा प्रोफाइल लॉगिन",
    "Create ABHA Number": "आभा संख्या बनाएं",
    "ABHA Enrollment using DL": "ड्राइविंग लाइसेंस द्वारा आभा पंजीकरण",
    "Find ABHA via Mobile": "मोबाइल द्वारा आभा खोजें",
    "Choose the document to register and generate a new ABHA identity": "पंजीकरण और आभा पहचान बनाने के लिए दस्तावेज चुनें",
    "Enter your 10-digit mobile number linked to your ABHA profile.": "आभा प्रोफाइल से लिंक अपना 10-अंकीय मोबाइल नंबर दर्ज करें।",
    "Verify your identity using Aadhaar-linked mobile secure OTP.": "आधार-लिंक मोबाइल सुरक्षित ओटीपी का उपयोग करके अपनी पहचान सत्यापित करें।",
    "Enter your 14-digit ABHA Number or ABHA Address (@sbx).": "अपनी 14-अंकीय आभा संख्या या आभा पता (@sbx) दर्ज करें।",
    "Create your unique 14-digit ABHA number using Aadhaar secure OTP.": "आधार सुरक्षित ओटीपी का उपयोग करके अपनी विशिष्ट 14-अंकीय आभा संख्या बनाएं।",
    "Enter your mobile number to request a DL verification OTP.": "ड्राइविंग लाइसेंस सत्यापन ओटीपी का अनुरोध करने के लिए मोबाइल नंबर दर्ज करें।",
    "Locate your ABHA profiles linked with your mobile number.": "अपने मोबाइल नंबर से लिंक आभा प्रोफाइल का पता लगाएं।",
    "Select a profile below to log in directly.": "सीधे लॉगिन करने के लिए नीचे से एक प्रोफाइल चुनें।",
    "An OTP has been sent to the mobile number registered with your Driving License.": "आपके ड्राइविंग लाइसेंस से पंजीकृत मोबाइल नंबर पर ओटीपी भेजा गया है।",
    "An OTP has been sent to your registered mobile number.": "आपके पंजीकृत मोबाइल नंबर पर ओटीपी भेजा गया है।"
  },
  TA: {
    "Your Digital": "உங்கள் டிஜிட்டல்",
    "Healthcare Ecosystem": "சுகாதார சுற்றுச்சூழல் அமைப்பு",
    "Book Consultation": "ஆலோசனை முன்பதிவு",
    "Book Doctor": "டாக்டரை பதிவு செய்யவும்",
    "Health ATM": "சுகாதார ஏடிஎம்",
    "Digital Locker": "டிஜிட்டல் லாக்கர்",
    "Health Locker": "சுகாதார லாக்கர்",
    "Quick Access": "விரைவு அணுகல்",
    "View All": "அனைத்தையும் காட்டு",
    "Consult Doctor": "மருத்துவர் ஆலோசனை",
    "Order Medicines": "மருந்துகள் ஆர்டர்",
    "Book Lab Tests": "ஆய்வக சோதனை முன்பதிவு",
    "Manage Insurance": "காப்பீடு மேலாண்மை",
    "Training & Courses": "பயிற்சி மற்றும் படிப்புகள்",
    "Hospitals": "மருத்துவமனைகள்",
    "Blood Bank": "இரத்த வங்கி",
    "Organ Donation": "உறுப்பு தானம்",
    "QR Scanner": "கியூஆர் ஸ்கேனர்",
    "Create ABHA Card": "ஆபா அட்டை உருவாக்கு",
    "Live Health Dashboard": "நேரடி சுகாதார டேஷ்போர்டு",
    "AI Alerts": "AI விழிப்பூட்டல்கள்",
    "Device Sync": "சாதன ஒத்திசைவு",
    "Telemedicine": "டெலிமெடிசின்",
    "Video / Audio Consultation": "வீடியோ / ஆடியோ ஆலோசனை",
    "Connect with doctors instantly": "மருத்துவர்களுடன் உடனே இணையுங்கள்",
    "Join Now": "இப்போது இணையுங்கள்",
    "Waiting Room": "காத்திருப்பு அறை",
    "Patients Ahead": "நோயாளி முன்னே உள்ளனர்",
    "Est. 8 mins wait": "சுமார் 8 நிமிட காத்திருப்பு",
    "Multi-Doctor": "பல மருத்துவர்",
    "Conference": "மாநாடு",
    "Connect with specialists": "நிபுணர்களுடன் இணையுங்கள்",
    "Marketplace": "சந்தைப்பகுதி",
    "Medicine Delivery": "மருந்து விநியோகம்",
    "Lab Booking": "ஆய்வக முன்பதிவு",
    "Home Sample Collection": "வீட்டு மாதிரி சேகரிப்பு",
    "Medical Equipment": "மருத்துவ உபகரணங்கள்",
    "Ambulance Booking": "ஆம்புலன்ஸ் முன்பதிவு",
    "Drone Delivery": "ட்ரோன் விநியோகம்",
    "Coming Soon": "விரைவில் வரும்",
    "Medicolegal & Compliance": "மருத்துவச் சட்டம் & இணக்கம்",
    "Medicolegal Support": "சட்ட மருத்துவ ஆதரவு",
    "Digital Consent Forms": "டிஜிட்டல் ஒப்புதல் படிவங்கள்",
    "Prescription Verification": "மருந்துச்சீட்டு சரிபார்ப்பு",
    "Secure Health Records": "பாதுகாப்பான சுகாதார பதிவுகள்",
    "Telemedicine Compliance": "டெலிமெடிசின் இணக்கம்",
    "Legal Docs Vault": "சட்ட ஆவணங்கள் பாதுகாப்பு பெட்டகம்",
    "ABDM Compliant": "ABDM இணக்கமானது",
    "HIPAA Secure": "HIPAA பாதுகாப்பானது",
    "GDPR Ready": "GDPR தயாராக உள்ளது",
    "DPDP Compliant": "DPDP இணக்கமானது",
    "Health Insights & Education": "சுகாதார நுண்ணறிவு மற்றும் கல்வி",
    "Health Tips": "சுகாதார குறிப்புகள்",
    "Daily tips for a healthy life": "ஆரோக்கியமான வாழ்க்கைக்கான தினசரி குறிப்புகள்",
    "Appointment Reminders": "சந்திப்பு நினைவூட்டல்கள்",
    "Never miss your appointments": "உங்கள் சந்திப்புகளை தவறவிடாதீர்கள்",
    "Preventive Care": "தடுப்பு பராமரிப்பு",
    "Regular checkups for a better you": "சிறந்த ஆரோக்கியத்திற்கு வழக்கமான சோதனைகள்",
    "Chronic Disease Programs": "நாள்பட்ட நோய் திட்டங்கள்",
    "Specialized care for chronic conditions": "நாள்பட்ட நோய்களுக்கான சிறப்பு சிகிச்சை",
    "AI Health Assistant": "AI சுகாதார உதவியாளர்",
    "Your smart health companion": "உங்கள் ஸ்மார்ட் சுகாதார துணையாக",
    "Home": "முகப்பு",
    "Health": "சுகாதாரம்",
    "Appointments": "சந்திப்புகள்",
    "Records": "பதிவுகள்",
    "More": "மேலும்",
    "Link Hospital Records": "மருத்துவமனை பதிவுகளை இணைக்கவும்",
    "Share Records (Consent)": "பதிவுகளை பகிரவும் (ஒப்புதல்)",
    "Scan & Share (OPD)": "ஸ்கேன் & ஷேர் (OPD)",
    "Search Doctors & Book": "மருத்துவர்களை தேடி முன்பதிவு செய்க",
    "Insurance Claims": "காப்பீட்டு கோரிக்கைகள்",
    "Doctor Registry (HPR)": "மருத்துவர் பதிவேடு (HPR)",
    "Developer Sandbox Tests": "டெवलப்பர் சாண்ட்பாக்ஸ் சோதனைகள்",
    "Login": "உள்நுழை",
    "Create ABHA": "ஆபாவை உருவாக்கு",
    "Find ABHA": "ஆபாவைக் கண்டுபிடி",
    "Get Started": "தொடங்குங்கள்",
    "Preferred": "விருப்பமான",
    "Select Login Method": "உள்நுழைவு முறையைத் தேர்ந்தெடுக்கவும்",
    "Select Registration Method": "பதிவு முறையைத் தேர்ந்தெடுக்கவும்",
    "Back to Menu": "முதன்மை மெனு",
    "Mobile OTP": "மொபைல் OTP",
    "Aadhaar": "ஆதார்",
    "ABHA ID": "ஆபா ஐடி",
    "Driving License": "ஓட்டுநர் உரிமம்",
    "Select Language": "மொழியைத் தேர்ந்தெடுக்கவும்",
    "Verify & Continue": "சரிபார்த்து தொடரவும்",
    "Send OTP": "ஓடிபி அனுப்பு",
    "Back": "பின்விவரம்",
    "Cancel": "ரத்து செய்",
    "An OTP has been sent to the mobile number registered with your Driving License.": "உங்கள் ஓட்டுநர் உரிமத்துடன் பதிவு செய்யப்பட்ட மொபைல் எண்ணுக்கு OTP அனுப்பப்பட்டுள்ளது.",
    "An OTP has been sent to your registered mobile number.": "பதிவுசெய்யப்பட்ட உங்கள் மொபைல் எண்ணுக்கு OTP அனுப்பப்பட்டுள்ளது."
  },
  TE: {
    "Your Digital": "మీ డిజిటల్",
    "Healthcare Ecosystem": "ఆరోగ్య సంరక్షణ వ్యవస్థ",
    "Book Consultation": "కన్సల్టేషన్ బుక్ చేయండి",
    "Book Doctor": "డాక్టర్‌ను బుక్ చేయండి",
    "Health ATM": "హెల్త్ ఏటిఎం",
    "Digital Locker": "డిజిటల్ లాకర్",
    "Health Locker": "హెల్త్ లాకర్",
    "Quick Access": "త్వరిత ప్రాప్యత",
    "View All": "అన్నీ చూడండి",
    "Consult Doctor": "డాక్టర్‌ను సంప్రదించండి",
    "Order Medicines": "మందులను ఆర్డర్ చేయండి",
    "Book Lab Tests": "ల్యాబ్ పరీక్షలను బుక్ చేయండి",
    "Manage Insurance": "ఇన్సూరెన్స్ నిర్వహించండి",
    "Training & Courses": "శిక్షణ & కోర్సులు",
    "Hospitals": "ఆసుపత్రులు",
    "Blood Bank": "బ్లడ్ బ్యాంక్",
    "Organ Donation": "అవయవ దానం",
    "QR Scanner": "QR స్కానర్",
    "Create ABHA Card": "ఆభా కార్డును సృష్టించండి",
    "Live Health Dashboard": "లైవ్ హెల్త్ డాష్‌బోర్డ్",
    "AI Alerts": "AI హెచ్చరికలు",
    "Device Sync": "పరికర సింక్",
    "Telemedicine": "టెలిమెడిసిన్",
    "Video / Audio Consultation": "వీడియో / ఆడియో కన్సల్టేషన్",
    "Connect with doctors instantly": "డాక్టర్లతో తక్షణమే కనెక్ట్ అవ్వండి",
    "Join Now": "ఇప్పుడే చేరండి",
    "Waiting Room": "వెయిటింగ్ రూమ్",
    "Patients Ahead": "ముందున్న రోగులు",
    "Est. 8 mins wait": "సుమారు 8 నిమిషాల నిరీక్షణ",
    "Multi-Doctor": "మల్టీ-డాక్టర్",
    "Conference": "కాన్ఫరెన్స్",
    "Connect with specialists": "నిపుణులతో కనెక్ట్ అవ్వండి",
    "Marketplace": "మార్కెట్‌ప్లేస్",
    "Medicine Delivery": "మందుల డెలివరీ",
    "Lab Booking": "ల్యాబ్ బుకింగ్",
    "Home Sample Collection": "హోమ్ శాంపిల్ కలెక్షన్",
    "Medical Equipment": "వైద్య పరికరాలు",
    "Ambulance Booking": "అంబులెన్స్ బుకింగ్",
    "Drone Delivery": "డ్రోన్ డెలివరీ",
    "Coming Soon": "త్వరలో రాబోతోంది",
    "Medicolegal & Compliance": "మెడికోలీగల్ & కంప్లయన్స్",
    "Medicolegal Support": "మెడికోలీగల్ సపోర్ట్",
    "Digital Consent Forms": "డిజిటల్ సమ్మతి ఫారమ్‌లు",
    "Prescription Verification": "ప్రిస్క్రిప్షన్ వెరిఫికేషన్",
    "Secure Health Records": "సురక్షిత ఆరోగ్య రికార్డులు",
    "Telemedicine Compliance": "టెలిమెడిసిన్ కంప్లయన్స్",
    "Legal Docs Vault": "లీగల్ డాక్స్ వాల్ట్",
    "ABDM Compliant": "ABDM కంప్లయంట్",
    "HIPAA Secure": "HIPAA సురక్షితం",
    "GDPR Ready": "GDPR సిద్ధం",
    "DPDP Compliant": "DPDP కంప్లయంట్",
    "Health Insights & Education": "ఆరోగ్య అంతర్దృష్టులు & విద్య",
    "Health Tips": "ఆరోగ్య చిట్కాలు",
    "Daily tips for a healthy life": "ఆరోగ్యకరమైన జీవితం కోసం రోజువారీ చిట్కాలు",
    "Appointment Reminders": "అపాయింట్‌మెంట్ రిమైండర్‌లు",
    "Never miss your appointments": "మీ అపాయింట్‌మెంట్‌లను ఎప్పటికీ కోల్పోకండి",
    "Preventive Care": "నివారణ సంరక్షణ",
    "Regular checkups for a better you": "మెరుగైన ఆరోగ్యం కోసం క్రమం తప్పకుండా తనిఖీలు",
    "Chronic Disease Programs": "దీర్ఘకాలిక వ్యాధి కార్యక్రమాలు",
    "Specialized care for chronic conditions": "దీర్ఘకాలిక పరిస్థితుల కోసం ప్రత్యేక సంరక్షణ",
    "AI Health Assistant": "AI హెల్త్ అసిస్టెంట్",
    "Your smart health companion": "మీ స్మార్ట్ హెల్త్ కంపానియన్",
    "Home": "హోమ్",
    "Health": "ఆరోగ్యం",
    "Appointments": "అపాయింట్‌మెంట్‌లు",
    "Records": "రికార్డులు",
    "More": "మరిన్ని",
    "Link Hospital Records": "హాస్పిటల్ రికార్డులను లింక్ చేయండి",
    "Share Records (Consent)": "రికార్డులను షేర్ చేయండి (సమ్మతి)",
    "Scan & Share (OPD)": "స్కాన్ & షేర్ (OPD)",
    "Search Doctors & Book": "డాక్టర్లను వెతకండి & బుక్ చేయండి",
    "Insurance Claims": "ఇన్సూరెన్స్ క్లెయిమ్‌లు",
    "Doctor Registry (HPR)": "డాక్టర్ రిజిస్ట్రీ (HPR)",
    "Developer Sandbox Tests": "డెవలపర్ శాండ్‌బాక్స్ పరీక్షలు",
    "Login": "లాగిన్",
    "Create ABHA": "ఆభా సృష్టించండి",
    "Find ABHA": "ఆభాను కనుగొనండి",
    "Get Started": "ప్రారంభించండి",
    "Preferred": "ప్రాధాన్యత",
    "Select Login Method": "లాగిన్ పద్ధతిని ఎంచుకోండి",
    "Select Registration Method": "రిజిస్ట్రేషన్ పద్ధతిని ఎంచుకోండి",
    "Back to Menu": "ప్రధాన మెనూ",
    "Mobile OTP": "మొబైల్ OTP",
    "Aadhaar": "ఆధార్",
    "ABHA ID": "ఆభా ఐడి",
    "Driving License": "డ్రైవింగ్ లైసెన్స్",
    "Select Language": "భాషను ఎంచుకోండి",
    "Verify & Continue": "ధృవీకరించి కొనసాగించండి",
    "Send OTP": "ఓటిపి పంపండి",
    "Back": "వెనుకకు",
    "Cancel": "రద్దు చేయి",
    "An OTP has been sent to the mobile number registered with your Driving License.": "మీ డ్రైవింగ్ లైసెన్స్‌తో నమోదైన మొబైల్ నంబర్‌కు OTP పంపబడింది.",
    "An OTP has been sent to your registered mobile number.": "మీ నమోదిత మొబైల్ నంబర్‌కు OTP పంపబడింది."
  },
  BN: {
    "Your Digital": "আপনার ডিজিটাল",
    "Healthcare Ecosystem": "স্বাস্থ্যসেবা ইকোসিস্টেম",
    "Book Consultation": "পরামর্শ বুক করুন",
    "Book Doctor": "ডাক্তার বুক করুন",
    "Health ATM": "হেলথ এটিএম",
    "Digital Locker": "ডিজিটাল লকার",
    "Health Locker": "হেলথ লকার",
    "Quick Access": "দ্রুত অ্যাক্সেস",
    "View All": "সব দেখুন",
    "Consult Doctor": "ডাক্তার দেখান",
    "Order Medicines": "ওষুধ অর্ডার করুন",
    "Book Lab Tests": "ল্যাব টেস্ট বুক করুন",
    "Manage Insurance": "বীমা পরিচালনা করুন",
    "Training & Courses": "প্রশিক্ষণ ও কোর্স",
    "Hospitals": "হাসপাতাল",
    "Blood Bank": "ব্লাড ব্যাংক",
    "Organ Donation": "অঙ্গদান",
    "QR Scanner": "কিউআর স্ক্যানার",
    "Create ABHA Card": "আভা কার্ড তৈরি করুন",
    "Live Health Dashboard": "লাইভ স্বাস্থ্য ড্যাশবোর্ড",
    "AI Alerts": "এআই অ্যালার্ট",
    "Device Sync": "ডিভাইস সিঙ্ক",
    "Telemedicine": "টেলিমেডিসিন",
    "Video / Audio Consultation": "ভিডিও / অডিও পরামর্শ",
    "Connect with doctors instantly": "ডাক্তারদের সাথে সাথে সাথে যোগাযোগ করুন",
    "Join Now": "এখনই যোগ দিন",
    "Waiting Room": "অপেক্ষার ঘর",
    "Patients Ahead": "রোগী আগে আছেন",
    "Est. 8 mins wait": "আনুমানিক ৮ মিনিট অপেক্ষা",
    "Multi-Doctor": "মাল্টি-ডাক্তার",
    "Conference": "কনফারেন্স",
    "Connect with specialists": "বিশেষজ্ঞদের সাথে যোগাযোগ করুন",
    "Marketplace": "মার্কেটপ্লেস",
    "Medicine Delivery": "ওষুধ সরবরাহ",
    "Lab Booking": "ল্যাব বুকিং",
    "Home Sample Collection": "হোম স্যাম্পল কালেকশন",
    "Medical Equipment": "চিকিৎসা সরঞ্জাম",
    "Ambulance Booking": "অ্যাম্বুলেন্স বুকিং",
    "Drone Delivery": "ড্রোন ডেলিভারি",
    "Coming Soon": "শীঘ্রই আসছে",
    "Medicolegal & Compliance": "মেডিকোলেগাল ও কমপ্লায়েন্স",
    "Medicolegal Support": "মেডিকোলেগাল সহায়তা",
    "Digital Consent Forms": "ডিজিটাল সম্মতি ফর্ম",
    "Prescription Verification": "প্রেসক্রিপশন যাচাইকরণ",
    "Secure Health Records": "সুরক্ষিত স্বাস্থ্য রেকর্ড",
    "Telemedicine Compliance": "টেলিমেডিসিন কমপ্লায়েন্স",
    "Legal Docs Vault": "আইনি নথি ভল্ট",
    "ABDM Compliant": "ABDM অনুগত",
    "HIPAA Secure": "HIPAA সুরক্ষিত",
    "GDPR Ready": "GDPR প্রস্তুত",
    "DPDP Compliant": "DPDP অনুগত",
    "Health Insights & Education": "স্বাস্থ্য অন্তর্দৃষ্টি ও শিক্ষা",
    "Health Tips": "স্বাস্থ্য টিপস",
    "Daily tips for a healthy life": "সুস্থ জীবনের জন্য দৈনিক টিপস",
    "Appointment Reminders": "অ্যাপয়েন্টমেন্ট অনুস্মারক",
    "Never miss your appointments": "আপনার অ্যাপয়েন্টমেন্ট মিস করবেন না",
    "Preventive Care": "প্রতিরোধমূলক যত্ন",
    "Regular checkups for a better you": "একটি ভাল আপনার জন্য নিয়মিত পরীক্ষা",
    "Chronic Disease Programs": "দীর্ঘস্থায়ী রোগ প্রোগ্রাম",
    "Specialized care for chronic conditions": "দীর্ঘস্থায়ী অবস্থার জন্য বিশেষ যত্ন",
    "AI Health Assistant": "এআই স্বাস্থ্য সহকারী",
    "Your smart health companion": "আপনার smart স্বাস্থ্য সঙ্গী",
    "Home": "হোম",
    "Health": "স্বাস্থ্য",
    "Appointments": "অ্যাপয়েন্টমেন্ট",
    "Records": "রেকর্ড",
    "More": "আরো",
    "Link Hospital Records": "হাসপাতাল রেকর্ড লিঙ্ক করুন",
    "Share Records (Consent)": "রেকর্ড শেয়ার করুন (সম্মতি)",
    "Scan & Share (OPD)": "স্ক্যান ও শেয়ার (OPD)",
    "Search Doctors & Book": "ডাক্তার খুঁজুন ও বুক করুন",
    "Insurance Claims": "বীমা দাবি (ক্লেম)",
    "Doctor Registry (HPR)": "ডাক্তার রেজিস্ট্রি (HPR)",
    "Developer Sandbox Tests": "ডেভেলপার স্যান্ডবক্স টেস্ট",
    "Login": "লগইন",
    "Create ABHA": "আভা তৈরি করুন",
    "Find ABHA": "আভা খুঁজুন",
    "Get Started": "শুরু করুন",
    "Preferred": "পছন্দসই",
    "Select Login Method": "লগইন পদ্ধতি নির্বাচন করুন",
    "Select Registration Method": "নিবন্ধন পদ্ধতি নির্বাচন করুন",
    "Back to Menu": "প্রধান মেনু",
    "Mobile OTP": "মোবাইল ওটিপি",
    "Aadhaar": "আধার",
    "ABHA ID": "আভা আইডি",
    "Driving License": "ড্রাইভিং লাইসেন্স",
    "Select Language": "ভাষা নির্বাচন করুন",
    "Verify & Continue": "যাচাই করুন এবং এগিয়ে যান",
    "Send OTP": "ওটিপি পাঠান",
    "Back": "পিছনে",
    "Cancel": "বাতিল করুন",
    "An OTP has been sent to the mobile number registered with your Driving License.": "আপনার ড্রাইভিং লাইসেন্সের সাথে নিবন্ধিত মোবাইল নম্বরে ওটিপি পাঠানো হয়েছে।",
    "An OTP has been sent to your registered mobile number.": "আপনার নিবন্ধিত মোবাইল নম্বরে ওটিপি পাঠানো হয়েছে।"
  },
  MR: {
    "Your Digital": "तुमची डिजिटल",
    "Healthcare Ecosystem": "आरोग्य सेवा इकोसिस्टम",
    "Book Consultation": "सल्लामसलत बुक करा",
    "Book Doctor": "डॉक्टर बुक करा",
    "Health ATM": "हेल्थ एटीएम",
    "Digital Locker": "डिजिटल लॉकर",
    "Health Locker": "हेल्थ लॉकर",
    "Quick Access": "त्वरित प्रवेश",
    "View All": "सर्व पहा",
    "Consult Doctor": "डॉक्टरांचा सल्ला घ्या",
    "Order Medicines": "औषधे ऑर्डर करा",
    "Book Lab Tests": "लॅब चाचण्या बुक करा",
    "Manage Insurance": "विमा व्यवस्थापित करा",
    "Training & Courses": "प्रशिक्षण आणि अभ्यासक्रम",
    "Hospitals": "रुग्णालये",
    "Blood Bank": "ब्लड बँक",
    "Organ Donation": "अवयव दान",
    "QR Scanner": "क्यूआर स्कॅनर",
    "Create ABHA Card": "आभा कार्ड बनवा",
    "Live Health Dashboard": "लाइव्ह हेल्थ डॅशबोर्ड",
    "AI Alerts": "एआय अलर्ट",
    "Device Sync": "डिव्हाइस सिंक",
    "Telemedicine": "टेलीमेडिसिन",
    "Video / Audio Consultation": "व्हिडिओ / ऑडिओ सल्लामसलत",
    "Connect with doctors instantly": "डॉक्टरांशी त्वरित संपर्क साधा",
    "Join Now": "आता सामील व्हा",
    "Waiting Room": "प्रतिक्षा कक्ष",
    "Patients Ahead": "रुग्ण पुढे आहेत",
    "Est. 8 mins wait": "अंदाजे ८ मिनिटे प्रतीक्षा",
    "Multi-Doctor": "मल्टी-डॉक्टर",
    "Conference": "परिषद",
    "Connect with specialists": "तज्ञांशी संपर्क साधा",
    "Marketplace": "मार्केटप्लेस",
    "Medicine Delivery": "औषध वितरण",
    "Lab Booking": "लॅब बुकिंग",
    "Home Sample Collection": "घरी नमुना संकलन",
    "Medical Equipment": "वैद्यकीय उपकरणे",
    "Ambulance Booking": "अँबुलन्स बुकिंग",
    "Drone Delivery": "ड्रोन डिलिव्हरी",
    "Coming Soon": "लवकरच येत आहे",
    "Medicolegal & Compliance": "मेडिकोलीगल आणि अनुपालन",
    "Medicolegal Support": "मेडिकोलीगल समर्थन",
    "Digital Consent Forms": "डिजिटल संमती फॉर्म",
    "Prescription Verification": "प्रिस्क्रिप्शन पडताळणी",
    "Secure Health Records": "सुरक्षित आरोग्य रेकॉर्ड",
    "Telemedicine Compliance": "टेलीमेडिसिन अनुपालन",
    "Legal Docs Vault": "कायदेशीर दस्तऐवज वॉल्ट",
    "ABDM Compliant": "ABDM सुसंगत",
    "HIPAA Secure": "HIPAA सुरक्षित",
    "GDPR Ready": "GDPR तयार",
    "DPDP Compliant": "DPDP सुसंगत",
    "Health Insights & Education": "आरोग्य अंतर्दृष्टी आणि शिक्षण",
    "Health Tips": "आरोग्य टिप्स",
    "Daily tips for a healthy life": "निरोगी आयुष्यासाठी रोजच्या टिप्स",
    "Appointment Reminders": "अपॉइंटमेंट स्मरणपत्रे",
    "Never miss your appointments": "तुमची अपॉइंटमेंट कधीही चुकवू नका",
    "Preventive Care": "प्रतिबंधात्मक काळजी",
    "Regular checkups for a better you": "चांगल्या आरोग्यासाठी नियमित तपासणी",
    "Chronic Disease Programs": "तीव्र रोग कार्यक्रम",
    "Specialized care for chronic conditions": "तीव्र आजारांसाठी विशेष काळजी",
    "AI Health Assistant": "एआय आरोग्य सहाय्यक",
    "Your smart health companion": "तुमचा स्मार्ट आरोग्य सोबती",
    "Home": "होम",
    "Health": "आरोग्य",
    "Appointments": "अपॉइंटमेंट",
    "Records": "रेकॉर्ड",
    "More": "अधिक",
    "Link Hospital Records": "रुग्णालय रेकॉर्ड लिंक करा",
    "Share Records (Consent)": "रेकॉर्ड सामायिक करा (सहमती)",
    "Scan & Share (OPD)": "स्कॅन आणि शेअर (ओपीडी)",
    "Search Doctors & Book": "डॉक्टर शोधा आणि बुक करा",
    "Insurance Claims": "विमा दावे (क्लेम्स)",
    "Doctor Registry (HPR)": "डॉक्टर नोंदणी (HPR)",
    "Developer Sandbox Tests": "डेव्हलपर सँडबॉक्स चाचण्या",
    "Login": "लॉगिन",
    "Create ABHA": "आभा तयार करा",
    "Find ABHA": "आभा शोधा",
    "Get Started": "सुरू करा",
    "Preferred": "प्राधान्य",
    "Select Login Method": "लॉगिन पद्धत निवडा",
    "Select Registration Method": "नोंदणी पद्धत निवडा",
    "Back to Menu": "मुख्य मेनू",
    "Mobile OTP": "मोबाईल ओटीपी",
    "Aadhaar": "आधार",
    "ABHA ID": "आभा आयडी",
    "Driving License": "ड्रायव्हिंग लायसन्स",
    "Select Language": "भाषा निवडा",
    "Verify & Continue": "सत्यापित करा आणि सुरू ठेवा",
    "Send OTP": "ओटीपी पाठवा",
    "Back": "मागे",
    "Cancel": "रद्द करा",
    "An OTP has been sent to the mobile number registered with your Driving License.": "तुमच्या ड्रायव्हिंग लायसन्सशी नोंदणीकृत मोबाईल नंबरवर ओटीपी पाठवला गेला आहे।",
    "An OTP has been sent to your registered mobile number.": "तुमच्या नोंदणीकृत मोबाईल नंबरवर ओटीपी पाठवला गेला आहे।"
  },
  GU: {
    "Your Digital": "તમારું ડિજિટલ",
    "Healthcare Ecosystem": "હેલ્થકેર ઇકોસિસ્ટમ",
    "Book Consultation": "પરામર્શ બુક કરો",
    "Book Doctor": "ડોક્ટર બુક કરો",
    "Health ATM": "હેલ્થ એટીએમ",
    "Digital Locker": "ડિજિટલ લોકર",
    "Health Locker": "હેલ્થ લોકર",
    "Quick Access": "ઝડપી પ્રવેશ",
    "View All": "બધું જુઓ",
    "Consult Doctor": "ડોક્ટરની સલાહ",
    "Order Medicines": "દવાઓ ઓર્ડર કરો",
    "Book Lab Tests": "લેબ ટેસ્ટ બુક કરો",
    "Manage Insurance": "વીમો સંચાલિત કરો",
    "Training & Courses": "તાલીમ અને અભ્યાસક્રમો",
    "Hospitals": "હોસ્પિટલો",
    "Blood Bank": "બ્લડ બેંક",
    "Organ Donation": "અંગ દાન",
    "QR Scanner": "ક્યૂઆર સ્કેનર",
    "Create ABHA Card": "આભા કાર્ડ બનાવો",
    "Live Health Dashboard": "લાઇવ હેલ્થ ડેશબોર્ડ",
    "AI Alerts": "એઆઈ એલર્ટ",
    "Device Sync": "ડિવાઇસ સિંક",
    "Telemedicine": "ટેલીમેડિસિન",
    "Video / Audio Consultation": "વિડિઓ / ઓડિયો પરામર્શ",
    "Connect with doctors instantly": "ડોકટરો સાથે તરત જ જોડાઓ",
    "Join Now": "હમણાં જોડાઓ",
    "Waiting Room": "પ્રતીક્ષા ખંડ",
    "Patients Ahead": "દર્દીઓ આગળ છે",
    "Est. 8 mins wait": "આશરે ૮ મિનિટ પ્રતીક્ષા",
    "Multi-Doctor": "મલ્ટી-ડોક્ટર",
    "Conference": "કોન્ફરન્સ",
    "Connect with specialists": "નિષ્ણાતો સાથે જોડાઓ",
    "Marketplace": "માર્કેટપ્લેસ",
    "Medicine Delivery": "દવા વિતરણ",
    "Lab Booking": "લેબ બુકિંગ",
    "Home Sample Collection": "ઘરે સેમ્પલ કલેક્શન",
    "Medical Equipment": "તબીબી સાધનો",
    "Ambulance Booking": "એમ્બ્યુલન્સ બુકિંગ",
    "Drone Delivery": "ડ્રોન ડિલિવરી",
    "Coming Soon": "ટૂંક સમયમાં આવી રહ્યું છે",
    "Medicolegal & Compliance": "મેડિકોલીગલ અને અનુપાલન",
    "Medicolegal Support": "મેડિકોલીગલ સપોર્ટ",
    "Digital Consent Forms": "ડિજિટલ સંમતિ પત્રો",
    "Prescription Verification": "પ્રિસ્ક્રિપ્શન ચકાસણી",
    "Secure Health Records": "સુરક્ષિત આરોગ્ય રેકોર્ડ્સ",
    "Telemedicine Compliance": "ટેલીમેડિસિન અનુપาลન",
    "Legal Docs Vault": "કાનૂની દસ્તાવેજો વોલ્ટ",
    "ABDM Compliant": "ABDM સુસંગત",
    "HIPAA Secure": "HIPAA સુરક્ષિત",
    "GDPR Ready": "GDPR તૈયાર",
    "DPDP Compliant": "DPDP સુસંગત",
    "Health Insights & Education": "આરોગ્ય આંતરદૃષ્ટિ અને શિક્ષણ",
    "Health Tips": "આરોગ્ય ટિપ્સ",
    "Daily tips for a healthy life": "સ્વસ્થ જીવન માટે દૈનિક ટિપ્સ",
    "Appointment Reminders": "એપોઇન્ટમેન્ટ રીમાઇન્ડર્સ",
    "Never miss your appointments": "તમારી એપોઇન્ટમેન્ટ ક્યારેય ચૂકશો નહીં",
    "Preventive Care": "નિવારક સંભાળ",
    "Regular checkups for a better you": "વધુ સારા સ્વાસ્થ્ય માટે નિયમિત તપાસ",
    "Chronic Disease Programs": "ક્રોનિક રોગ કાર્યક્રમો",
    "Specialized care for chronic conditions": "ક્રોનિક રોગો માટે ખાસ કાળજી",
    "AI Health Assistant": "એઆઈ આરોગ્ય સહાયક",
    "Your smart health companion": "તમારો સ્માર્ટ આરોગ્ય સાથી",
    "Home": "હોમ",
    "Health": "આરોગ્ય",
    "Appointments": "એપોઇન્ટમેન્ટ",
    "Records": "રેકોર્ડ્સ",
    "More": "વધુ",
    "Link Hospital Records": "હોસ્પિટલ રેકોર્ડ લિંક કરો",
    "Share Records (Consent)": "રેકોર્ડ શેર કરો (સંમતિ)",
    "Scan & Share (OPD)": "સ્કેન અને શેર (OPD)",
    "Search Doctors & Book": "ડોક્ટર શોધો અને બુક કરો",
    "Insurance Claims": "વીમા દાવાઓ",
    "Doctor Registry (HPR)": "ડોક્ટર રજિસ્ટ્રી (HPR)",
    "Developer Sandbox Tests": "ડેવલપર સેન્ડબોક્સ ટેસ્ટ",
    "Login": "લૉગિન",
    "Create ABHA": "આભા બનાવો",
    "Find ABHA": "આભા શોધો",
    "Get Started": "શરૂ કરો",
    "Preferred": "પસંદગીનું",
    "Select Login Method": "લૉગિન પદ્ધતિ પસંદ કરો",
    "Select Registration Method": "નોંધણી પદ્ધતિ પસંદ કરો",
    "Back to Menu": "મુખ્ય મેનુ",
    "Mobile OTP": "મોબાઇલ OTP",
    "Aadhaar": "આધાર",
    "ABHA ID": "આભા આઈડી",
    "Driving License": "ડ્રાઇવિંગ લાઇસન્સ",
    "Select Language": "ભાષા પસંદ કરો",
    "Verify & Continue": "ચકાસો અને આગળ વધો",
    "Send OTP": "ઓટીપી મોકલો",
    "Back": "પાછા જાઓ",
    "Cancel": "રદ કરો",
    "An OTP has been sent to the mobile number registered with your Driving License.": "તમારા ડ્રાઇવિંગ લાઇસન્સ સાથે રજીસ્ટર્ડ મોબાઇલ નંબર પર OTP મોકલવામાં આવ્યો છે.",
    "An OTP has been sent to your registered mobile number.": "તમારા રજીસ્ટર્ડ મોબાઇલ નંબર પર OTP મોકલવામાં આવ્યો છે."
  },
  KN: {
    "Your Digital": "ನಿಮ್ಮ ಡಿಜಿಟಲ್",
    "Healthcare Ecosystem": "ಆರೋಗ್ಯ ರಕ್ಷಣೆ ಪರಿಸರ ವ್ಯವಸ್ಥೆ",
    "Book Consultation": "ಸಮಾಲೋಚನೆ ಬುಕ್ ಮಾಡಿ",
    "Book Doctor": "ವೈದ್ಯರನ್ನು ಬುಕ್ ಮಾಡಿ",
    "Health ATM": "ಹೆಲ್ತ್ ಎಟಿಎಂ",
    "Digital Locker": "ಡಿಜಿಟಲ್ ಲಾಕರ್",
    "Health Locker": "ಹೆಲ್ತ್ ಲಾಕರ್",
    "Quick Access": "ತ್ವರಿತ ಪ್ರವೇಶ",
    "View All": "ಎಲ್ಲವನ್ನೂ ವೀಕ್ಷಿಸಿ",
    "Consult Doctor": "ವೈದ್ಯರನ್ನು ಸಂಪರ್ಕಿಸಿ",
    "Order Medicines": "ಔಷಧಿಗಳನ್ನು ಆರ್ಡರ್ ಮಾಡಿ",
    "Book Lab Tests": "ಲ್ಯಾಬ್ ಪರೀಕ್ಷೆಗಳನ್ನು ಬುಕ್ ಮಾಡಿ",
    "Manage Insurance": "ವಿಮೆಯನ್ನು ನಿರ್ವಹಿಸಿ",
    "Training & Courses": "ತರಬೇತಿ ಮತ್ತು ಕೋರ್ಸ್‌ಗಳು",
    "Hospitals": "ಆಸ್ಪತ್ರೆಗಳು",
    "Blood Bank": "ರಕ್ತನಿಧಿ",
    "Organ Donation": "ಅಂಗದಾನ",
    "QR Scanner": "ಕ್ಯೂಆರ್ ಸ್ಕ್ಯಾನರ್",
    "Create ABHA Card": "ಆಭಾ ಕಾರ್ಡ್ ರಚಿಸಿ",
    "Live Health Dashboard": "ಲೈವ್ ಹೆಲ್ತ್ ಡ್ಯಾಶ್‌ಬೋರ್ಡ್",
    "AI Alerts": "ಎಐ ಎಚ್ಚರಿಕೆಗಳು",
    "Device Sync": "ಡಿವೈಸ್ ಸಿಂಕ್",
    "Telemedicine": "ಟೆಲಿಮೆಡಿಸಿನ್",
    "Video / Audio Consultation": "ವಿಡಿಯೋ / ಆಡಿಯೋ ಸಮಾಲೋಚನೆ",
    "Connect with doctors instantly": "ವೈದ್ಯರೊಂದಿಗೆ ತಕ್ಷಣ ಸಂಪರ್ಕ ಸಾಧಿಸಿ",
    "Join Now": "ಈಗಲೇ ಸೇರಿಕೊಳ್ಳಿ",
    "Waiting Room": "ಕಾಯುವ ಕೊಠಡಿ",
    "Patients Ahead": "ರೋಗಿಗಳು ಮುಂದೆ ಇದ್ದಾರೆ",
    "Est. 8 mins wait": "ಅಂದಾಜು 8 ನಿಮಿಷ ಕಾಯುವಿಕೆ",
    "Multi-Doctor": "ಮಲ್ಟಿ-ಡಾಕ್ಟರ್",
    "Conference": "ಕಾನ್ಫರೆನ್ಸ್",
    "Connect with specialists": "ತಜ್ಞರೊಂದಿಗೆ ಸಂಪರ್ಕ ಸಾಧಿಸಿ",
    "Marketplace": "ಮಾರುಕಟ್ಟೆ",
    "Medicine Delivery": "ಔಷಧಿ ವಿತರಣೆ",
    "Lab Booking": "ಲ್ಯಾಬ್ ಬುಕಿಂಗ್",
    "Home Sample Collection": "ಮನೆಯಲ್ಲಿ ಮಾದರಿ ಸಂಗ್ರಹಣೆ",
    "Medical Equipment": "ವೈದ್ಯಕೀಯ ಉಪಕರಣಗಳು",
    "Ambulance Booking": "ಆಂಬ್ಯುಲೆನ್ಸ್ ಬುಕಿಂಗ್",
    "Drone Delivery": "ಡ್ರೋನ್ ಡೆಲಿವರಿ",
    "Coming Soon": "ಶೀಘ್ರದಲ್ಲೇ ಬರಲಿದೆ",
    "Medicolegal & Compliance": "ಮೆಡಿಕೋಲೀಗಲ್ ಮತ್ತು ಅನುಸರಣೆ",
    "Medicolegal Support": "ಮೆಡಿಕೋಲೀಗಲ್ ಬೆಂಬಲ",
    "Digital Consent Forms": "ಡಿಜಿಟಲ್ ಒಪ್ಪಿಗೆ ಪತ್ರಗಳು",
    "Prescription Verification": "ಪ್ರಿಸ್ಕ್ರಿಪ್ಷನ್ ಪರಿಶೀಲನೆ",
    "Secure Health Records": "ಸುರಕ್ಷಿತ ಆರೋಗ್ಯ ದಾಖಲೆಗಳು",
    "Telemedicine Compliance": "ಟೆಲಿಮೆಡಿಸಿನ್ ಅನುಸರಣೆ",
    "Legal Docs Vault": "ಕಾನೂನು ದಾಖಲೆಗಳ ವಾಲ್ಟ್",
    "ABDM Compliant": "ABDM ಕಂಪ್ಲైಂಟ್",
    "HIPAA Secure": "HIPAA ಸುರಕ್ಷಿತ",
    "GDPR Ready": "GDPR ಸಿದ್ಧ",
    "DPDP Compliant": "DPDP ಕಂಪ್ಲైಂಟ್",
    "Health Insights & Education": "ಆರೋಗ್ಯ ಒಳನೋಟಗಳು ಮತ್ತು ಶಿಕ್ಷಣ",
    "Health Tips": "ಆರೋಗ್ಯ ಸಲಹೆಗಳು",
    "Daily tips for a healthy life": "ಆರೋಗ್ಯಕರ ಜೀವನಕ್ಕಾಗಿ ದೈನಂದิน ಸಲಹೆಗಳು",
    "Appointment Reminders": "ಅಪಾಯಿಂಟ್‌ಮೆಂಟ್ ಜ್ಞಾಪನೆಗಳು",
    "Never miss your appointments": "ನಿಮ್ಮ ಅಪಾಯಿಂಟ್‌ಮೆಂಟ್‌ಗಳನ್ನು ಎಂದಿಗೂ ತಪ್ಪಿಸಬೇಡಿ",
    "Preventive Care": "ತಡೆಗಟ್ಟುವ ಆರೈಕೆ",
    "Regular checkups for a better you": "ಉತ್ತಮ ಆರೋಗ್ಯಕ್ಕಾಗಿ ನಿಯಮಿತ ತಪಾಸಣೆ",
    "Chronic Disease Programs": "ದೀರ್ಘಕಾಲದ ಕಾಯಿಲೆ ಕಾರ್ಯಕ್ರಮಗಳು",
    "Specialized care for chronic conditions": "ದೀರ್ಘಕಾಲದ ಕಾಯಿಲೆಗಳಿಗೆ ವಿಶೇಷ ಆರೈಕೆ",
    "AI Health Assistant": "ಎಐ ಆರೋಗ್ಯ ಸಹಾಯಕ",
    "Your smart health companion": "ನಿಮ್ಮ ಸ್ಮಾರ್ಟ್ ಆರೋಗ್ಯ ಒಡನಾಡಿ",
    "Home": "ಹೋಮ್",
    "Health": "ಆರೋಗ್ಯ",
    "Appointments": "ನೇಮಕಾতিಗಳು",
    "Records": "ದಾಖಲೆಗಳು",
    "More": "ಇನ್ನಷ್ಟು",
    "Link Hospital Records": "ಆಸ್ಪತ್ರೆ ದಾಖಲೆಗಳನ್ನು ಲಿಂಕ್ ಮಾಡಿ",
    "Share Records (Consent)": "ದಾಖಲೆಗಳನ್ನು ಹಂಚಿಕೊಳ್ಳಿ (ಸಮ್ಮತಿ)",
    "Scan & Share (OPD)": "ಸ್ಕ್ಯಾನ್ ಮತ್ತು ಶೇರ್ (OPD)",
    "Search Doctors & Book": "ವೈದ್ಯರನ್ನು ಹುಡುಕಿ ಮತ್ತು ಬುಕ್ ಮಾಡಿ",
    "Insurance Claims": "ವಿಮಾ ಹಕ್ಕುಗಳು",
    "Doctor Registry (HPR)": "ವೈದ್ಯರ ನೋಂದಣಿ (HPR)",
    "Developer Sandbox Tests": "ಡೆವಲಪರ್ ಸ್ಯಾಂಡ್‌ಬಾಕ್ಸ್ ಪರೀಕ್ಷೆಗಳು",
    "Login": "ಲಾಗಿನ್",
    "Create ABHA": "ಆಭಾ ರಚಿಸಿ",
    "Find ABHA": "ಆಭಾ ಹುಡುಕಿ",
    "Get Started": "ಪ್ರಾರಂಭಿಸಿ",
    "Preferred": "ಆದ್ಯತೆ",
    "Select Login Method": "ಲಾಗಿನ್ ವಿಧಾನವನ್ನು ಆಯ್ಕೆಮಾಡಿ",
    "Select Registration Method": "ನೋಂದಣಿ ವಿಧಾನವನ್ನು ಆಯ್ಕೆಮಾಡಿ",
    "Back to Menu": "ಮುಖ್ಯ ಮೆನು",
    "Mobile OTP": "ಮೊಬೈಲ್ OTP",
    "Aadhaar": "ಆಧಾರ್",
    "ABHA ID": "ಆಭಾ ಐಡಿ",
    "Driving License": "ಚಾಲನಾ ಪರವಾನಗಿ",
    "Select Language": "ಭಾಷೆಯನ್ನು ಆಯ್ಕೆಮಾಡಿ",
    "Verify & Continue": "ಪರಿಶೀಲಿಸಿ ಮತ್ತು ಮುಂದುವರಿಸಿ",
    "Send OTP": "ಓಟಿಪಿ ಕಳುಹಿಸಿ",
    "Back": "ಹಿಂದಕ್ಕೆ",
    "Cancel": "ರದ್ದುಗೊಳಿಸಿ",
    "An OTP has been sent to the mobile number registered with your Driving License.": "ನಿಮ್ಮ ಚಾಲನಾ ಪರವಾನಗಿಯೊಂದಿಗೆ ನೋಂದಾಯಿಸಲಾದ ಮೊಬೈಲ್ ಸಂಖ್ಯೆಗೆ OTP ಕಳುಹಿಸಲಾಗಿದೆ.",
    "An OTP has been sent to your registered mobile number.": "ನಿಮ್ಮ ನೋಂದಾಯಿತ ಮೊಬೈಲ್ ಸಂಖ್ಯೆಗೆ OTP ಕಳುಹಿಸಲಾಗಿದೆ."
  }
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguageState] = useState<LanguageCode>('EN');

  useEffect(() => {
    try {
      const state = JSON.parse(localStorage.getItem('setu_state') || '{}');
      if (state.language) {
        setLanguageState(state.language);
      }
    } catch (e) {
      console.error(e);
    }
  }, []);

  const setLanguage = (lang: LanguageCode) => {
    setLanguageState(lang);
    try {
      const state = JSON.parse(localStorage.getItem('setu_state') || '{}');
      state.language = lang;
      localStorage.setItem('setu_state', JSON.stringify(state));
    } catch (e) {
      console.error(e);
    }
  };

  const t = (key: string): string => {
    const table = translations[language];
    if (table && table[key]) {
      return table[key];
    }
    return key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}
